### ISSUE TITLE
Support all keywords for plantuml

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#102]
As mentioned in https://github.com/hallvard/plantuml/issues/59 a syntax highlighting for all plantuml keywords shall be added to the AsciiDoctorPlantUMLEditor

This is the replacement for https://github.com/hallvard/plantuml/issues/60 where I accidently addedan issue for asciidoctor editor...

**Comment by paulvi** [comment]
It is even more awesome now
