### ISSUE TITLE
Also highlight _Text_

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#109]
Asciidoc supports also the underscore for highlighting words. Would be nice to highlight them also in the editor.

![image](https://user-images.githubusercontent.com/139910/41651323-9698aa4c-7480-11e8-8e82-3ac942f22bcc.png)

**Comment by de-jcup** [comment]
Is italic

see https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#formatted-text

and this is already fixed with
https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/100

**Comment by vogella** [comment]
Nice. Thanks

Albert Tregnaghi <notifications@github.com> schrieb am Mi., 20. Juni 2018,
12:03:
