### ISSUE TITLE
Support short cuts for some toolbaractions

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#111]
- [ ] 'CTRL + b' should make the text bold
- [ ] 'CTRL + i' should make the text italic
- [ ] 'CTRL + m' should make the monospace

**Comment by 51x31** [comment]
ShortCuts for toolbaractions sounds very good.

One schould also implement those usecases with commands and handlers in the eclipse ecosystem and not as jface-actions as it was done in `/asciidoctor-editor-plugin/src/main/java-eclipse/de/jcup/asciidoctoreditor/AsciiDoctorEditor.java`

**pros:**
* use commands everywhere in the eclipse ide (if you want to)
* avoid manual imagedescriptor handling (creation, destruction)
* declare keybindings in plugin.xml

**Comment by de-jcup** [comment]
I normally use also commands and use editor context to prevent problems with other existing short cuts in other context. The only reason I was using actions in this case was: Wanting a dedicated toolbar the actions where "the easisest way". 

In this issue the shortcuts will be done by commands. 

Thanx.

**Comment by de-jcup** [comment]
Interesting : https://stackoverflow.com/questions/21851929/jface-swt-what-is-the-best-way-to-add-a-toolbar-with-commands-to-a-section

**Comment by de-jcup** [comment]
Maybe it would be wise to completely change the toolbar to command behaviour. Should be possible as described by Lars at http://www.vogella.com/tutorials/EclipseCommands/article.html#application-toolbar-coolbar

**Comment by de-jcup** [comment]
After having read https://stackoverflow.com/questions/15949320/eclipse-rcp-can-i-add-a-toolbar-to-an-editor-part I will keep the actions as they are. Editors having their own toolbar seems to be a little bit "exotic" and are not supported out of the box by eclipse.

But having an own toolbar inside editor is necessary and makes still sense.

**Comment by de-jcup** [comment]
Commands now shown inside context menu of editor or in source menu as well.
Or just here the shortcuts
```
CTRL + I  = italic
CTRL + B  = bold
CTRL + X  = monospaced
```
