### ISSUE TITLE
Lists are rendered as bold

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#113]
Currently, list elements are rendered bold, which is not how the result is rendered. I suggest to render lists as normal text.

````
* this is the first 
* the second
* why should this bold?

````

**Comment by de-jcup** [comment]
FormattedTextFinder must be refactored one of its method is extreme big ...

**Comment by de-jcup** [comment]
Now correct rendererd. Also other formatting problems are fixed. 

![image](https://user-images.githubusercontent.com/11644753/42274206-1c110316-7f8c-11e8-8e72-cc93769610e2.png)
