### ISSUE TITLE
Include on bigger documents have often problems

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#114]
I still have often the problem that includes used in subfiles are not correctly shown.

The mechanism to resolve root dir goes too much deep.
```

/src/docs/asciidoctor
    gen/generated_01.adoc
    shared/shared01.adoc (includes ./../gen/generated_01.adoc)
    techdoc/chapter1/ch01_text.adoc (includes ./../shared/shared01.adoc)
 main.adoc
``` 
In such a combination e.g. the shared01.adoc has problems, because currently the rootfolder detection
mechanism will go to src/docs/asciidoctor because there is the root for .adoc files

Asciidoc files are always relative to their own position when doing includes. So the resolving of 
src/docs/asciidoctor as doc folder will result in problem that the include cannot be rendered by
asciidoctor.

The image mechanism to fetch the root image path etc. is okay. But not this one.

Should have some junit test to prevent those siutations again!

**Comment by de-jcup** [comment]
Moved to 1.1.0 because this takes more time and 1.0.1 should be released

**Comment by de-jcup** [comment]
There is also a comment inside #90  about those situations.

**Comment by de-jcup** [comment]
Hmm... currently I am having no such problems and I do also not have any example code to correctly reproduce.

So decided to move to next milestone.

**Comment by de-jcup** [comment]
Funny : using Version 1.2.0 now and having again such a problem, when switching to `installed asciidoctor` the problem disappears and includes are resolved. Switching back the problems appear again and having  an output like

```
Unresolved directive in 06_runtime_view.adoc - include::./../gen/gen_usecases.adoc[]
Unresolved directive in 06_runtime_view.adoc - include::./../gen/gen_uc_restdoc.adoc[]
```
Either it has to do with asciidoctor variant or the adoptions of outdir in execution phase?

**Comment by de-jcup** [comment]
On the other side installed asciidoctor with default options has problems with diagram including! see #161

**Comment by de-jcup** [comment]
There is still an issue if somebody has multiple document folders, means multiple base dirs.

**Comment by de-jcup** [comment]
Described base dir resolving at https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/FAQ#base-dir-resolving

**Comment by de-jcup** [comment]
Hmm.. refresh does not rebuild cached base dir completely.

**Comment by de-jcup** [comment]
@vogella Could you do me a favour and checkout https://github.com/de-jcup/eclipse-asciidoctor-editor/commit/38e78148904913b24b6c0304d962fc6e3f2111d1 - or master HEAD - and test if the includes now working with your documentation setups much more better? There should be no longer any include problems. 

I tried it with one of my bigger documentation projects and did no longer found any problems - no matter if I am using  installed asciidoctor or embedded one, nor if using external or internal previews.

Thanx a lot ...

**Comment by vogella** [comment]
I don't use the internal build so I don't think I'm a good tester for this. I always build outside of Eclipse via the command line.
