### ISSUE TITLE
Passing options to asciidoctor 

### ISSUE THREAD

**Issue by mako4** [de-jcup/eclipse-asciidoctor-editor#116]
It would be great to have a way to pass options to asciidoctor for the document conversion (like stylesheets or custom extensions). The main advantage (for me, anyway) would be to be able to have the same look and feel as in the published version of the document. 

I don't know what the simplest way would be to add (in the CLI it would just be a string with the the parameters, I don't know how it works for the java library).

**Comment by de-jcup** [comment]
Hello @mako4 , I will give it a try ... When its easy to establish I will setup a preference entry where you can can setup some provided options

**Comment by de-jcup** [comment]
Hello @mako4 ,
when adding just a preference page with a table which gives access to
https://asciidoctor.org/docs/user-manual/#ruby-api-options
users would also be able to block some of the workarounds I did for the editor outputs etc. means a little bit dangerous and also generating support issues for problems coming up when using options etc. wrong (e.g. baseDir setting generates issue about "No longer output in editor")

So my next thoughts where it would be safer and also more comfortable to
- add custom extensions 
- add custom template directories
by dedicated preference page entries.

But looking into code for enabling embedded variants having access to extensions outside... having here customization could be also problematic. (Compatibility etc.)

So I will try another approach and will start #147 - so users area able to use an existing asciidoctor instance installed on system. In this case full access to cli options, attributes etc. will be possible.

I hope this approach will help you.

**Comment by de-jcup** [comment]
With #147 you can use installed asciidoctor and use custom CLI options as well. So I close the issue
