### ISSUE TITLE
Missing include file - Option to create it

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#118]
Instead of saying the file could not be created, we could also offer to create it.

![image](https://user-images.githubusercontent.com/139910/42206658-1072cb3c-7ea8-11e8-982f-e2baf5e59e83.png)

**Comment by de-jcup** [comment]
Nice idea. Added to next milestone.

**Comment by 51x31** [comment]
i get the following message in the preview window when i include a missingfile:
![missingfile](https://user-images.githubusercontent.com/16285444/42279291-9cda3786-7f9d-11e8-8a77-bdf7541795af.png)

how can i reproduce the above message?

**Comment by de-jcup** [comment]
Done with #122 
@51x31  thanx a lot

**Comment by de-jcup** [comment]
### Notice about nice additional feature behaviour

The implementation does now enable users to create not only .adoc files but every referenced file.
So e.g. a 

`ditaa::fileName.ditaa[format=png, title="title"]`

link will automatically create the missing ditaa file as well!
