### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by sjaeckel** [de-jcup/eclipse-asciidoctor-editor#121]
I just tried to install on Eclipse Photon (4.8.0) and that's the error I got:

```
Unable to read repository at https://dl.bintray.com/de-jcup/asciidoctoreditor/content.xml.
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

**Comment by de-jcup** [comment]
Maybe this is an issue with your JRE - please look into https://github.com/de-jcup/eclipse-jenkins-editor/issues/38 where another user had similar problems.

He used Open JDK 11.
After using a JDK 8 on starting eclipse all was working fine.

**Comment by sjaeckel** [comment]
Looks like this doesn't help anymore! I get the same error :(

```
$ apt-cache show openjdk-8-jre
Package: openjdk-8-jre
Architecture: amd64
Version: 8u171-b11-0ubuntu0.18.04.1
...
```

and eclipse also tells me that this one is used via the "Configuration" tab in the "Eclipse IDE Installation Details"

```
...
-vm
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
...
eclipse.vm=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
eclipse.vmargs=-Dosgi.requiredJavaVersion=1.8
...
```

**Comment by sjaeckel** [comment]
https://gist.github.com/mikaelhg/527204e746984cf9a33f7910bb8b4cb6 which was mentioned in https://github.com/docker-library/openjdk/issues/145#issuecomment-385181287 helped
