### ISSUE TITLE
Hyperlinking of diagrams not working

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#123]
When you have setup a link to a diagram for example:
`plantuml::diagrams/diagram1.plantuml[format=svg, alt="Class diagram1"] `
the Hyperlink is not working and a question about to create the missing file is shown.

But the diagrams pathes are established from root folder and not as normally by includeds from current file in a relative way.

For images this does work correctly. Must be fixed for diagrams as well . Even when we got no special imagesDir attribute but must just resolve the root folder.

**Comment by 51x31** [comment]
did not know that there is a difference...

to clarify: 

1. paths for includes (also including images) are relative paths starting at the current active file in editor
2. paths for diagrams like plantuml or ditaa have absolute paths?
2.1. "absolute paths" as seen from the current workspace or absolute paths starting at your harddrive?

i could try to fix this in some days ;)

**Comment by de-jcup** [comment]
We must differ between "relative, absolute and from root". Normally you should never use absolute pathes. The output does contain absolute pathes but no document should use something in such way.
"From root" - means from current base directory (this is tried to resolve by an algorithm )
"Relative" from current file

**To your questions:**
1. Path for includes: either relative or absolute. See https://asciidoctor.org/docs/user-manual/#include-resolution for official statement - currently only relative supported, absolute makes normally no sense because document would only work on same strucutres, but could be supported in future.

2. Paths for diagrams: I currently do not know the official statement - but theres seems to be no special directive (like "imagesDir") which defines those. When trying out I recognized that alwas basedir is used for diagram resolution. So a link like `plantuml::diagrams/diagram1.plantuml[format=svg, alt="Class diagram1"]` will be resolved by `/$baseDir/diagrams/diagram1.plantuml`

Best way to implement would be:
Refactor `AsciiDoctorEditorLinkTextHyperlinkDetector`
and establish a dedicated resolveLinkToDiagram(linkText...) (see line 66)
and differ includes from diagrams by using own hyperlink etc.

So there is a bigger refactoring to be done.
@51x31 Do you still want to do this or should I simply do the changes?

**Comment by 51x31** [comment]
sorry, for the late response. i'm very busy this week.
hmm that sounds, you should do the changes. 

i need some time to get deeper into the code.

**Comment by de-jcup** [comment]
Ok. I will do the changes in next time.
