### ISSUE TITLE
Support line/block commenting for plantuml Editor

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-asciidoctor-editor#125]
plantuml comment is single quite sign `'`

Please support coloring for comments (usually green)
and shortcut like `Ctrl+/` for commenting line or selected lines

```
'http://plantuml.com/sequence-diagram defines grammer
participant System
```

**Comment by de-jcup** [comment]
Commenting in plantuml is described here:

http://forum.plantuml.net/1353/is-it-possible-to-comment-out-lines-of-diagram-syntax

![image](https://user-images.githubusercontent.com/11644753/45519516-aaf5d000-b7b5-11e8-90b9-0e46d9ac2b7b.png)

Pressing now CTRL+7 leads to

![image](https://user-images.githubusercontent.com/11644753/45519584-fdcf8780-b7b5-11e8-9307-9b42afff5a88.png)

Pressing CTRL+7 again leads to

![image](https://user-images.githubusercontent.com/11644753/45519516-aaf5d000-b7b5-11e8-90b9-0e46d9ac2b7b.png)
