### ISSUE TITLE
Support for SDEDIT

### ISSUE THREAD

**Issue by RiSchuster** [de-jcup/eclipse-asciidoctor-editor#127]
What about the support for sedit ?

**Comment by de-jcup** [comment]
Currently I did event not know 
http://sdedit.sourceforge.net/

There exists a asciidoctor extension:
https://github.com/domgold/asciidoctor-sdedit-extension which is
listed at 
https://asciidoctor.org/docs/extensions/

Currently It is not planned to support sedit directly/in an embedded way.

But maybe it would be nice to have ability to add extensions at all?
So I created isseu #128 to have possibility to add custom asciidoctor extensions - so this would support then sedit too.

**Comment by de-jcup** [comment]
With https://github.com/domgold/asciidoctor-sdedit-extension + upcoming version containing #147 you should be able to use sdedit inside the editor. Normally you just have install the extension by using ruby `gem install ...`  and references the libary with e.g.` -r asciidoctor-sdedit` by additional CLI arguments in preferences.

So I close the issue.
