### ISSUE TITLE
Text formatting inconsistencies

### ISSUE THREAD

**Issue by sjaeckel** [de-jcup/eclipse-asciidoctor-editor#131]
These issues are all related to https://asciidoctor.org/docs/user-manual/#text-formatting

1. The highlighting of _italic_, **bold** or `monospaced` words in the editor is only working when the end-ticks are followed by a space or new-line.

e.g. this fails to highlight any of them
```
_foo_`bar`*baz*
_foo_*bar*`baz`_qux_*quux*
```

2. The highlighting of the `__`, `**`  resp.` `` ` operators isn't implemented at all.

e.g. this fails to highlight any of them
```
__foo__o o**bar**``baz``*qux*
```

The generated output in both cases also looks unexpected sometimes ;)

**Comment by de-jcup** [comment]
I think this has been already solved with #139
