### ISSUE TITLE
Checkboxes are not rendered

### ISSUE THREAD

**Issue by 51x31** [de-jcup/eclipse-asciidoctor-editor#133]
check boxes like
`* [ ] do something` 
are not rendered in preview window. Only the text (do something) gets rendered.

**Comment by de-jcup** [comment]
With version 1.0.1 I tried the examples from
https://asciidoctor.org/docs/user-manual/#checklist :

```
* [*] checked
* [x] also checked
* [ ] not checked
*     normal list item
```
I got following result:

![image](https://user-images.githubusercontent.com/11644753/42900222-a4c8d89a-8ac8-11e8-8d11-040b007f564c.png)

So it seems it is working...

**Comment by de-jcup** [comment]
By the way: the "preview" is rendered by real asciidoctor instance and viewed inside an embedded system browser. So the output should normally not differ to a "normal" asciidoctor output - e.g. done by a gradle build.
