### ISSUE TITLE
Absolute file path used in img src attribute confuses Firefox on Windows

### ISSUE THREAD

**Issue by kwah-gh** [de-jcup/eclipse-asciidoctor-editor#134]
Preview in Firefox as "external" viewer on Windows does not show images in generated HTML. This is due to absolute file names used as img src attribute, example:
`<img src="C:/tmp/asciidoctor-editor-gen/editor_17977081791887/images/diagram1.png" alt="diagram1" width="120" height="126">`

Possible solutions:
1. Use relative path: `<img src="images/diagram1.png"`
2. Use proper file source: `<img src="file:///C:/tmp/asciidoctor-editor-gen/editor_17977081791887/images/diagram1.png" ...`

Since having absolute paths is not nice in general, the first option might be better.

**Comment by de-jcup** [comment]
You are right and I also prefer solution 1. Will be fixed.

The output with the absolute pathes is generated by asciidoctor itself - I think it comes up because I must set the target on startup of asciidoctor.

But I will change the preview files as suggested by you and so the problem will be fixed.

**Comment by de-jcup** [comment]
Maybe #74  could be solved in a familiar way

**Comment by kwah-gh** [comment]
Just a thought. I've seen in the code that there are absolute paths used to set attributes influencing [image output location](https://asciidoctor.org/docs/asciidoctor-diagram/#image-output-location) of asciidoctor diagram generator. Maybe it is influencing generated HTML then?

Default behavior of generator seem to be reasonable, and uses paths relative to asciidoc file being processed. It does not work without setting these attributes?

**Comment by de-jcup** [comment]
The image output location for diagrams is forced to an absolute path to prevent the generated diagrams appearing inside workspace (so only on temporary location). 

One of my targets when creating a eclipse plugin, is to make as less impact to other parts as possible. So I didn't want to hide generated diagrams inside an eclipse project by changing the project or adding an additional nature etc.

So the editor does use a temporary folder for asciidoc output and also generated diagrams.  To improve performance the editor does currently not copy all adoc files to temp folder and starts there but reuses file structure completely from project. Only additional resources like static images are copied back to temp folder.

So starting generation from project as base dir the image dir must be set absolute....

**Comment by kwah-gh** [comment]
Clear. Thank you for this elaborate explanation.
