### ISSUE TITLE
update bundled asciidoctor

### ISSUE THREAD

**Issue by sjaeckel** [de-jcup/eclipse-asciidoctor-editor#136]
there are some neat features in the latest asciidoctor 1.5.7 branch :)
would it be possible to get an updated version of this plugin which bundles the latest asciidoctor?

**Comment by de-jcup** [comment]
Hello @sjaeckel, 

the integration of asciidoctor into eclipse (in conjuction with asciidoctorj+ jruby + osgi...) was ... tricky.

Hmm... when looking at 
https://github.com/asciidoctor/asciidoctor/milestone/22?closed=1
https://github.com/asciidoctor/asciidoctor/milestone/27?closed=1

There was much going on in 1.5.7.x ... would be nice to get it.

I am currently not sure how much effort it would be to upgrade to 1.5.7. When no update of asciidoctorj and jruby would be necessary, It should be done very fast. But if some of the workarounds I integrated do no longer work with the new version... this could take some time...

I will give it a try - but currently I am extreme busy at my company, so I am not sure when I will be able to start. I start planning for 1.2.0

**Comment by charleech** [comment]
FYI, the [asciidoctorj version 1.5.7](https://github.com/asciidoctor/asciidoctorj/releases/tag/v1.5.7) is released as well. The `JRuby` supported version is `9.1.16.0`.

**Comment by de-jcup** [comment]
JRuby 9.x is/was a problem. I tried it out when I started the developing of the eclipse plugin and had many problems with it, so I did go back to 1.5.6 and  jruby-complete-1.7.26.jar. 

Maybe when implementing #69 and give users possibility to use a customized asciidoctorj + jruby setup the users could setup it by their own and if there is a working setup for newer asciidoctorj, the asciidoctor plugin could get some new library setup from community experience which is working well out of the box.

So maybe implementing #69 by customizable external asciidoctor setup and still providing 1.5.6 as embedded and stable variant, maybe this would be the smartest and easiest approach.

**Comment by sjaeckel** [comment]
I think so too, as my next question would've been "how can I enable asciidoctor-mathematical?"

**Comment by de-jcup** [comment]
#69 will be implemented

**Comment by de-jcup** [comment]
Closed #69 because #147 is now implemented and comes up with 1.2.0
So closing this issue too.
