### ISSUE TITLE
should have spell shecking

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-asciidoctor-editor#137]
Currently (asciidoctor-editor and) PlantUML editor do not have spell checking  
that leaves typos unnoticed.

**Comment by de-jcup** [comment]
Already implemented, see https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/99 done with version 1.0.0

**Comment by de-jcup** [comment]
@paulvi - works this for you? If so please close the issue. Thanks.

**Comment by paulvi** [comment]
OK
