### ISSUE TITLE
Wrong syntax highlighting

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#139]
Select _Manage Jenkins_ and then _Configure Global Security_.  is incorrectly rendered. _Configure Global Security_ is not using the same style as _Manage Jenkins_ 

![image](https://user-images.githubusercontent.com/139910/44578210-57cec580-a793-11e8-8287-93cbc2de9070.png)

**Comment by de-jcup** [comment]
Hm. Currently implementation does not handle syntax highlighting correct, when no whitespace is following. This will be generally fixed.
