### ISSUE TITLE
Wrong path for images used if ../ paths are usd

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#142]
The following path cannot be followed:

````
include::../RCP/008_content_introduction.adoc[]
````
![image](https://user-images.githubusercontent.com/139910/44721075-0c852180-aac9-11e8-891a-6b5963c82565.png)

**Comment by vogella** [comment]
cc @fapdash

**Comment by de-jcup** [comment]
Maybe this will be fixed with #114
