### ISSUE TITLE
Cancel Request not considered

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#144]
I have lots of "Initializing Asciidoctor" jobs running and slows down significantly Eclipse.
If I press Cancel nothing happens. Please consider adopting SubMonitor API as described here: https://www.eclipse.org/articles/Article-Progress-Monitors/article.html

![image](https://user-images.githubusercontent.com/139910/44874059-3e99ad80-ac9a-11e8-9449-034e17d2f7eb.png)

**Comment by de-jcup** [comment]
I had already some cancel mechanism inside, but when asciidoctor is started its hard to interrupt.
Maybe doing no update at all when you are using the external browser would be best - I will better explain my thoughts inside https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/143 which is related.

**Comment by de-jcup** [comment]
@vogella Is this still an issue or can we close this?

**Comment by de-jcup** [comment]
I think there is no longer a problem. So close issue

**Comment by vogella** [comment]
Thanks. Have not seen this in a while
