### ISSUE TITLE
Code completion for includes

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#145]
Would be cool to have code completion for includes.
````
include::../exercise_settings.adoc[]

include::../tutorials.eclipse/EclipseRCP/[CURSOR_HIER] -> Code completation available
include::../tutorials.eclipse/EclipseRCP/280_tutorial_processors.adoc[]
````

**Comment by de-jcup** [comment]
Jip cool idea, will come together with #89

**Comment by de-jcup** [comment]
There are bigger changes necessary here. Also when having many subfiles there is one question:
What is better: a code completion or a selection dialog? Hm. I am not sure.
Inside a selection dialog a scan would only be triggered when necessary but when every code completion starting would scan for new files etc. this would slow down (except when there would be a resource listener and cache etc. etc.) the editor code completion.

Another option would be to create a "smart code completion" where something like "include <selection>" would be visible in list and when choosen on auto completion a dialog would appear where a list of all subfiles + auto filtering would be enabled before inserting the real text.

Before I start implementing such a feature we should disuss which would be the best option here.

**Comment by vogella** [comment]
IMHO dialogs are a very bad UI pattern. In platform we want to get away from blocking dialog and move more to inline editing.

You should definitely use asynchronous code completion as we have implemented for the generic editor, all code completion proposals are calculated asynchronously. AFAIK Mickael also implemented also that code completion for custom editors can be asynchronous.

@mickaelistria do we have an example how to use this for custom editors?

**Comment by mickaelistria** [comment]
@vogella it's documented in https://www.eclipse.org/eclipse/news/4.7/M5/#async-content-assist

**Comment by vogella** [comment]
@mickaelistria thanks.

**Comment by vogella** [comment]
@mickaelistria as it is so easy we should adjust our own content assists in platform, e.g., the MANIFEST.MF one. I opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=539234 for this.

**Comment by de-jcup** [comment]
Thanks a lot. So the include code completion can be done, but It will be in a later version/milestone.

**Comment by de-jcup** [comment]
Will use https://github.com/de-jcup/eclipse-commons/issues/9 for model calculation after implemented...

**Comment by de-jcup** [comment]
Hmm.. I think a dedicated content assist, just inspecting the given text, knowing the editor file, should do the dynamic include without any project model build!

Will try this out in branch: 
`feature-145-tryout-localfile-possible-include-calculation`

**Comment by de-jcup** [comment]
There is also a need to accept plantuml and ditaa parts too.

**Comment by de-jcup** [comment]
All files must be includeable - see https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files
Text files , puml ,source code, etc. can be all part of an include!

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/59569820-3a0a7e00-908f-11e9-8d74-91189b286d53.png)

**Comment by de-jcup** [comment]
Added video to editor playlist at youtube: https://youtu.be/Bu_NMmVSt8M
