### ISSUE TITLE
Provide possibility to use existing Asciidoctor Instance instead embedded variant.

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#147]
### Wanted
There shall be the possiblity to use an existing asciidoctor installation instead of embedded variant.

This will solve #136 , #69  and also #116 .

The implementation will do a CLI call. This is for advanced users having their own working asciidoctor instance with custom templates, extensions etc.

### How to implement
This will be a full CLI call as done on console .

#### Optional
Having no embedded JRuby the cli call could show the asciidoc outputso in a dedicated console.

#### Remarks
Maybe parts of EGradle CLI handling could be copied and adapted...

**Comment by de-jcup** [comment]
It's now working. Maybe some finetuning necessary, but ... it is working :-) 

Users have now possibility to switch to installed version and give also additional CLI arguments. So full customizable...

![image](https://user-images.githubusercontent.com/11644753/46704603-0d62b480-cc2c-11e8-955d-0156afbe40ce.png)

**Comment by de-jcup** [comment]
Error output from asciidoctor instance is shown in own console:
![image](https://user-images.githubusercontent.com/11644753/46704718-8a8e2980-cc2c-11e8-9664-f45acc2a41c3.png)

**Comment by de-jcup** [comment]
Details about problems on rendering are found in error log, message contains information about command line string as well:

![image](https://user-images.githubusercontent.com/11644753/46704850-2ae44e00-cc2d-11e8-8cda-94130cd3f894.png)

**Comment by de-jcup** [comment]
### Just some documentation
The next pictures shows error outputs from installed asciidoctor (just misconfigured cli arguments in preferences by adding a `- unsupported-operation` as cli argument)

#### Syntax highlighting in console for errors
![image](https://user-images.githubusercontent.com/11644753/46732770-b510ce80-cc8e-11e8-8ea3-d1fa5b7b031b.png)

![image](https://user-images.githubusercontent.com/11644753/46732821-d671ba80-cc8e-11e8-916f-e5610b18ad99.png)
#### Errors are marked in problem view and editor
![image](https://user-images.githubusercontent.com/11644753/46732922-1f297380-cc8f-11e8-9d41-34324019b3a4.png)


![image](https://user-images.githubusercontent.com/11644753/46732883-015c0e80-cc8f-11e8-8034-2a873d906028.png)

**Comment by sjaeckel** [comment]
> Users have now possibility to switch to installed version and give also additional CLI arguments. So full customizable...

before you finish up working on it, would it be possible to have the option to give a path to the asciidoctor executable?
It's pretty useful to be able to use a different version than the one in the path

**Comment by de-jcup** [comment]
Okay, will implement. so reopen issue

**Comment by de-jcup** [comment]
@sjaeckel Is now configurable:

![image](https://user-images.githubusercontent.com/11644753/46865105-9a6c6000-ce1c-11e8-9b6a-ef74fd5fc167.png)

**Comment by de-jcup** [comment]
Without path set:
![image](https://user-images.githubusercontent.com/11644753/46865889-74948a80-ce1f-11e8-889c-6fde83d4331d.png)

**Comment by de-jcup** [comment]
@sjaeckel just released version 1.2.0 on marketplace
