### ISSUE TITLE
Add how to build to README.md

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#150]
Can you please add the build instructions to the README.md? `gradle build` or `gradle eclipse` do not bulid the asciidoctor-editor-updatesite

**Comment by vogella** [comment]
Background: I want the latest and greatest to get rid of the "Preview issue" and to provide faster feedback.

**Comment by de-jcup** [comment]
Hello Lars, 

In former commit I added a description in README.md for building the plugin / update site.

**A request by myself:**
Ahem... it's a little bit embarrassing, but currently I am not able to build my eclipse projects full with gradle (I wish I could but I did fail 2 years ago... always some dependencies were missing etc.). 

If you have a good working solution, a best practice example or a howto for an gradle approach please send me a link. 

I would like also to sign my plugins  as well and maybe this could be done with gradle in a convenient way - I also would prefer to have automated eclipse unit tests as well instead only testing non-eclipse parts and always wrap around...

**Comment by vogella** [comment]
I typically use Maven to build plugins so I don't know how to use Gradle
for that.

Albert Tregnaghi <notifications@github.com> schrieb am Mi., 19. Sep. 2018,
14:43:

**Comment by de-jcup** [comment]
So you are using tycho?

**Comment by vogella** [comment]
Yes

Albert Tregnaghi <notifications@github.com> schrieb am Do., 20. Sep. 2018,
08:58:

**Comment by de-jcup** [comment]
readme available so close issue
