### ISSUE TITLE
Asciidoctor preview jobs even though I do not want previews

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#160]
I never use the preview feature but it still runs and slows down my Eclipse.

![image](https://user-images.githubusercontent.com/139910/47555788-fe0e8700-d90c-11e8-800d-b27097a89548.png)

![image](https://user-images.githubusercontent.com/139910/47555816-12eb1a80-d90d-11e8-86d2-2af81a913cf0.png)

Would be great if the preview could avoided to be generated.

**Comment by de-jcup** [comment]
Please use latest version of the plugin. At preferences you will find a checkbox "Auto build for external preview" in preferences - should be turned off per default. 

So normally you should have your wanted behaviour out-of-the-box by simply updating plugin.

![image](https://user-images.githubusercontent.com/11644753/47638483-f7774e00-db5e-11e8-81d4-5c2c8c895c0c.png)

**Comment by de-jcup** [comment]
Implementation was done with https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/143.

**Comment by de-jcup** [comment]
Added FAQ entry about the feature, see https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/FAQ#how-can-i-turn-offon-building-asciidoctor-preview

**Comment by de-jcup** [comment]
@vogella can we close this ?

**Comment by de-jcup** [comment]
@vogella I think the problem no longer exists. So I close the issue. If you have still such problems, please just reopen the issue.

**Comment by vogella** [comment]
Thanks
