### ISSUE TITLE
[PlantUML Editor] option to automatically save .png preview

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-asciidoctor-editor#166]
Please add to PlantUML Editor option to automatically save .png preview,  
e.g. in the save folder and the same name, but .png extension  

![image](https://user-images.githubusercontent.com/1614482/48987583-6e523780-f15b-11e8-8b88-b81e2ddcbfa3.png)

**Comment by de-jcup** [comment]
@paulvi with #169 I consolidated the images output for a project. So no longer every editor got its own folder but a project shared one.

The PNGs are already generated. You will finde them (in upcoming V1.3.0) under
`$tempDir/asciidoctor-editor-temp/projec_$projectName$projectHashCode/images`

see also [Wiki](https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Technical-details#preview-files)

I think I could try to add a button which opens the images output folder per click or is the mentioned path enough for you?

**Comment by de-jcup** [comment]
Or a toolbar action `export` , maybe in combination with #173 would be very interesting.
So users could export the diagrams explicit to SVG or PNG

**Comment by paulvi** [comment]
The need for storing generated png within version control is to enable viewing on other computers, that may have different IDEs/tools.

I also often quickly share, once new UML is ready.  
And sharing within team is much easier with png image, that every one can see in instant messaging tool.

**Comment by de-jcup** [comment]
Per default disabled option, but can be found in preferences:
![image](https://user-images.githubusercontent.com/11644753/52540936-849d8600-2d8f-11e9-8b61-7d1dfe3e5c09.png)

**Comment by de-jcup** [comment]
When this is enabled and preview active, opening the editor or changing content will automatically create the png files to same location as editor file. Filename is editorFileName+image extension. Parent folder is automatially refreshed.

Here an example:

![image](https://user-images.githubusercontent.com/11644753/52540976-19a07f00-2d90-11e9-80d5-69d8a053e1fb.png)

**Comment by de-jcup** [comment]
@paulvi I just release V1.3.0 where feature is included.
