### ISSUE TITLE
Changed temporary file handling to project based approach

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#169]
Currently every editor does create its own tempfolder with its own structure inside etc.
But this (at least currently I think so )is nonsense when working on multiple files inside a project.

All temporary parts - e.g. images will be copied again and again, consume space and take time.
So it would be more nice to get the project of the editor, and create project related temp folders and reuse temporary data. This should be more efficent and faster. 
Maybe implementing this refactoring there could be also the include problem solved mentioned in #114

**Comment by khadarmaxamedaxmed9-hash** [comment]
Ethiopians  CBE
