### ISSUE TITLE
Dark theme color refactorings

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#174]
In the last time I was using dark theme on linux much often and ... I am not happy with current default colours for asciidoctor editor. I would like to define the defaults to look like the next example:

![image](https://user-images.githubusercontent.com/11644753/51248957-09180700-1992-11e9-9b89-f1a9ac086c2c.png)

With current default colors the former example looks like
![image](https://user-images.githubusercontent.com/11644753/51249292-2699a080-1993-11e9-9b0e-f33609061677.png)

@vogella : I would prefer my upper setup . It looks IMHO much more better than current.
Do you still prefer the current colors?

**Comment by vogella** [comment]
+1 for the new colour scheme

Am Mi., 16. Jan. 2019, 13:35 hat Albert Tregnaghi <notifications@github.com>
geschrieben:

**Comment by de-jcup** [comment]
When doing a change to dark theme you got now:
![image](https://user-images.githubusercontent.com/11644753/52523535-ddd3bf80-2c92-11e9-8099-6b1cc67e292d.png)

**Comment by de-jcup** [comment]
@vogella Its a little bit annoying that https://bugs.eclipse.org/bugs/show_bug.cgi?id=478835 is still not fixed (yes, yes I know, I could contribute... but I have currently not enough time, sorry).

So when users want to have the dark theme colors of this change apearing in their UI they have to switch back to light theme and back to dark theme...
