### ISSUE TITLE
Admonitions not correct shown at external preview with Firefox 64.0 on Linux

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#175]
I got following problem at an Ubuntu based Linux with Asciidoctor Editor 1.2.0:

![image](https://user-images.githubusercontent.com/11644753/51528220-787c7380-1e36-11e9-815a-d608fd0006f0.png)
results in external preview with Firefox 64.0 under Ubuntu based linux:
![image](https://user-images.githubusercontent.com/11644753/51527647-3272e000-1e35-11e9-8eb6-e97896852e87.png)
but in internal preview (which reuses Firefox) I correctly got:
![image](https://user-images.githubusercontent.com/11644753/51528332-b2e61080-1e36-11e9-8597-47bc65d6208d.png)

**Comment by de-jcup** [comment]
@vogella :As far as I know you are using Ubuntu + external preview. Have you also got those problems?

**Comment by vogella** [comment]
Works fine for me in Chrome but does not work in Firefox.

**Comment by de-jcup** [comment]
@vogella Thank you.

**Comment by de-jcup** [comment]
The "problem" is a security mechanism in firefox which prevents execution of local files
At web developer console there are entries like
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:/...`

**Comment by de-jcup** [comment]
**Solution / TODO:** 
With 1.3.0 we refactored behaviour of temporary files: Its now project dependent. So we can copy necessary parts (e.g. css folder) to the temp project files and replace 
html parts ala
`<link rel="stylesheet" href="file:/home/$user/.eclipse-asciidoctor-editor/css/1.0.0/font-awesome/css/font-awesome.min.css">`
with
`<link rel="stylesheet" href="css/1.0.0/font-awesome/css/font-awesome.min.css">`
It seems origin of local files is the root folder of the called html file. So it works  in firefox also external.
_(But i have still no idea why it works with cross origin policy problems in internal view at linux which is also Firefox..)_

**Comment by de-jcup** [comment]
With changes to ASP there was following changed as well:

- Internal preview: uses localfiles means css etc. provided by Asciidoctor Editor
- External preview: uses now origin links when ASP is used, when installed asciidoctor and full html is 
  provided, also original links (css, js etc.) from asciidoctor is used. When no valid html (means also no
   links) were generated by asciidoctor (depends on version and setup) as a fallback the local stylings will
   be used also

Normally this should work now without problems, so closing the issue.
