### ISSUE TITLE
Improve image template

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#176]
The JDT templates allow to to define placeholder, which can be used a tab jumping point. Maybe something similar can be offered for the image template:

JDT template example from /org.eclipse.jdt.ui/templates/default-templates.xml
```
<template name="if" description="%Templates.if" id="org.eclipse.jdt.ui.templates.if" context="java-statements" enabled="true" autoinsert="false">if (${condition:var(boolean)}) {
	${line_selection}${cursor}
}</template>
````

Would be nice to have image::imageName.png[]  and imageName selected so that is would be easier to change the image name for the user.

**Comment by de-jcup** [comment]
done with #82
