### ISSUE TITLE
Problems with cross reference labels (xreflabel) and scrolling

### ISSUE THREAD

**Issue by mschaufelberger** [de-jcup/eclipse-asciidoctor-editor#178]
Minimal example:
```
= My Title

See <<mysection>>.

[[mysection,here]]
== My Section
```
Leads to the following error log message if navigating to `[[mysection,here]]` with the cursor:
```
Was not able to execute javascript:document.getElementById('mysection,here').scrollIntoView();
```
When editing the document this errors occur quite often which slows down the whole platform and sometimes leads to "Abnormal Workbench Condition" error window popping up (which is why I discovered the error log messages).

Unlike for #177 (same symptom, different cause) there's a **workaround** for this one: define xreflabel in the reference usage instead of the reference definition, e.g.:
```
= My Title

See <<mysection,here>>.

[[mysection]]
== My Section
```

**Comment by de-jcup** [comment]
Probem is 
` sending javascript:doScrollTo('mysection,here')`

**Comment by mschaufelberger** [comment]
Great, thanks for fixing this!
