### ISSUE TITLE
Handling images when no imagedir set

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#183]
Maybe there exist problems when user do NOT define a image dir inside their .adoc files .

> Offline description:
> imagesdir 
> 
> The imagesdir document attribute can be used to specify the location of images that are referenced in the document using a relative path. 
> 
> We recommend using the imagesdir attribute to avoid hard-coding the common path to your images in every single image macro. 
> 
> The value of the imagesdir attribute can be an absolute path, relative path or URI. By default, the value of the imagesdir attribute is empty, which means these images are resolved relative to the document. If the image target is an absolute path or URI, the imagesdir prefix is not added to the path

**Comment by de-jcup** [comment]
@YuriBlankenstein Thank you for your contribution!

I have added 2 testprojects and made some minor changes. 
The text in preferences is now "Use image directory in preview folder" and I changed the name of preference, so when you install 1.3.0 you have to opt out again in preferences.

I introduced an enum for the image mode because I will need it for another feature.

Thank you for your help :+1: 
Best wishes 
Albert

**Comment by YuriBlankenstein** [comment]
Seems like you've been busy over the weekend Albert.
I do not have my imagedir set indeed, because of some other issues during my Maven build, you're right about that. I'm happy that I could contribute a bit to this nice editor. I already discovered that my option did lead to problems with generated plantuml images. Their images are generated in the source folder as well. So did you fix that with your enum solution?
Thanks for the great work!

**Comment by de-jcup** [comment]
### First of all 
My "Enum solution" does not fix this. I introduced enum because I needed it for https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/166 .

### Situation
Explanation: You set the imagesdir attribute to base dir . So without setting output directory explicit the images dir is used for output...

### Possible Solution
One option would be to bring up a text field in preferences which is enabled when option "Use image dir in preview folder" is turned off.
This value could be used to setup output image dir.

So you could enter e.g. "../build/asiidoc-diagrams" and diagrams should (hopefully) generated to this location. Also on option ala "$projectRoot/build/asciidoc-diagrams" would be maybe nice, so path handling would be easier (or just always using project root - which maybe would be simpler)
#### Preferred way
My preferred appraoch would be :
a) empty preference field - behave like current situation
b) default preference field to "build/asciidoc-diagrams"
c)  "build/asciidoc-diagrams" will be recalculated to $projectRoot/build/asciidc-diagrams. (so field
    entry always start from eclipse project root dir)
d) user have just to exclude "build" folder from scm (e.g. by .gitignore - which is done by gradle per default)

### Suggestion
If you like this possiblity please **create a new issue** (so your are the owner) and link to this one.
Maybe you want to implement also?
