### ISSUE TITLE
Update plantuml.jar

### ISSUE THREAD

**Issue by hong-chan** [de-jcup/eclipse-asciidoctor-editor#188]
The plantuml.jar looks outdated.

e.g. this cannot render:
```
[plantuml]
....
hide circle

entity Entity {
   * identifying_attribute
   --
   * mandatory_attribute
   optional_attribute
}

' zero or one
Entity |o--o| B

' exactly one
C ||--|| D

' zero or many
E }o--o{ Entity

' one or many
G }|--|{ H
....
```
but http://plantuml.com/ can.

**Comment by de-jcup** [comment]
Maybe I can update the jar at some time. In the mean time you could try to use a native asiidoctor variant instead of embedded one - see 
https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Using-installed-asciidoctor

Please give me feedback if this solves your problem.

**Comment by hbrands** [comment]
Or you can try to replace the plantuml.jar in your Eclipse installation with a newer version. For example in my installation it's found under 
plugins\de.jcup.asciidoctoreditor.libs_1.2.0\diagram\plantuml.jar

Use at your own risk! ;-)

(I had problems using the [C4-PlantUML](https://github.com/RicardoNiepel/C4-PlantUML) extension with the quite old PlantUML version used by this plugin.)

**Comment by de-jcup** [comment]
@hbrands  Thank you for suggestion, it brought this issue back to my attention ;-)
@hong-chan 
I will integrate newest one 2019.3 + add new language keywords also (if there are no regressions...)

**Comment by de-jcup** [comment]
**Just a related information:** 

While asciidoctor editor now use either installed asciidoctor or ASP (https://github.com/de-jcup/asp/) there is no longer a direct dependency to plantuml.jar

ASP uses asciidoctorj-diagram which contains suitable plantuml.jar - so every ASP update of dependencies will update plantuml like asciidoctorj defines.

![image](https://user-images.githubusercontent.com/11644753/76639376-4b18ea80-654e-11ea-95d7-85c1861dd716.png)
