### ISSUE TITLE
Idea: Click to Preview Header scrolls the Editor to the right position?

### ISSUE THREAD

**Issue by schittli** [de-jcup/eclipse-asciidoctor-editor#189]
Good evening
Thank you **very much** for this great Eclipse Addon!, it's very useful and the usability is better than many 'native' AsciiDoc Tools.

#### I've found a small issue:
Reading the AsciiDoc Document is much more useful in the preview. 
While reading, it often happens that I am searching for the right position in the Editor to modify the Text.

#### Therefore, it would be very useful if we could click e.g. Headers in the Preview 
and then, the Editor scrolls to the corresponding position.

Thanks a lot, kind regards,
Thomas

**Comment by de-jcup** [comment]
Interesting idea.
### Problems
- main problem is the call back from browser to eclipse.
- ... hmm... currently no other problems come up to my mind

### Potential solution
- To handle call backs the rendered output would have to more customized and javascript added
  So generate html ankers could make some some changes to a hidden div where the name name of current selected headline could be set. 
- A peridoc listener in editor could check if there is an entry there and read anker point (+reset in html doc per javascript).

**Comment by de-jcup** [comment]
Will implement this for 1.4.0 but by doing a browser.addMouseListener approach
