### ISSUE TITLE
Windows: GraphViz installed, eclipse-asciidoctor-editor says: No GraphViz installation found

### ISSUE THREAD

**Issue by schittli** [de-jcup/eclipse-asciidoctor-editor#190]
Good evening
Where does the eclipse-asciidoctor-editor Plugin search for GraphViz?
In Windows, I have 

1. installed GraphViz 2.38 stable for all users
2. manually set the System Path for all users
3. And in a Dos Shell (default and elevated), I can start dot.exe 

Unfortunately, the eclipse-asciidoctor-editor still says that it is not able to find GraphViz.
Does someone knows where it does search for it?

Thanks a lot for any help,
kind regards,
Thomas

**Comment by de-jcup** [comment]
I used graphviz on my windows machine a long time (I switched now to Linux, but did no changes).

Normally setting System path to have graphviz available does normally does it all.
I described at at 
https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/FAQ#plantuml-not-working

Normally this should not a problem when you have normally installed graphviz.

Have you installed asciidoctor editor newest version from eclipse marketplace?
If you have still problems maybe using native asciidoctor could solve the problem too:
https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Using-installed-asciidoctor

**Comment by schittli** [comment]
Hello de-jcup, 
thank you **very much** for your support!, I already followed the instructions in the [FAQ#plantuml-not-working](https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/FAQ#plantuml-not-working), but my Windows Eclipse Setup still ignored it.

But using the native AsciiDoctor Setup as described in your [Using installed asciidoctor](https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Using-installed-asciidoctor) description perfectly solved the Issue :-)

I just had to add the path to AsciiDoctor in the AsciiDoctor Editor Settings (`C:\Ruby25-x64\bin`).

Thanks a lot for your help!, kind regards, Thomas
