### ISSUE TITLE
ASP server always started

### ISSUE THREAD

**Issue by SubZeroPL** [de-jcup/eclipse-asciidoctor-editor#252]
I'm not sure if this was intentional change, but in commit [69bbd46](https://github.com/de-jcup/eclipse-asciidoctor-editor/commit/69bbd466afb708e343ce40f212d8f7ccc67ab757#diff-25cccbf3c3d54b6a4c216f6612edc2d4) method internalUpdateASPServerStart() in class ASPSupport was modified in such a way that currently ASP server is started even if user selects option to use locally installed Asciidoctor instead of ASP. 
This means it's currently not possible to activate the plugin without ASP libraries present/server running (which is exactly what i'm trying to achieve as i will only use my own installed instance of AsciidoctorJ).
Is that planned change, and if yes then is it now possible to use the pluging without ASP?

**Comment by de-jcup** [comment]
Hello @SubZeroPL , this was not planned but is just a stupid bug (maybe I should sleep more...). ! Thanks for reporting. 

Will be fixed.

**Comment by de-jcup** [comment]
Just released version 2.0.3 on eclipse marketplace with bugfix.

**Comment by SubZeroPL** [comment]
Now it's working fine, thanks :)
