### ISSUE TITLE
Using the imagesdir attribute

### ISSUE THREAD

**Issue by Kylja** [de-jcup/eclipse-asciidoctor-editor#257]
I would like to have several images folders in my project.
Setting the :imagesdir: attribute does not seem to resolve images as I would expect.
I have the following project structure:

# Project
.
 * [part1](./part1)
   * [assets](./part1/assets)
     * [images](./part1/assets/images)
       * [image1.pgn](./part1/assets/images/image1.pgn)
   * [documents](./part1/documents)
     * [doc1.adoc](./part1/documents/doc1.adoc)    
 * [part2](./part2)
   * [assets](./part2/assets)
     * [images](./part2/assets/images)
       * [image2.pgn](./part2/assets/images/image2.pgn)
   * [documents](./part2/documents)
     * [doc2.adoc](./part2/documents/doc2.adoc)    

In doc1.adoc I like to set :imagesdir: ../assets/images/

The setting of "use image directory in preview folder" does not seem to matter.

When I use {imagesdir} to show the value of imagesdir it shows the base folder without my relative path included. 

Reading the [Wiki ](https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Technical-details#how-does-the-hiden-temporary-file-appraoch-work)
Did not help me understand what i'm doing wrong.
I'm using installed asciidoctor

**Comment by de-jcup** [comment]
Hello @Kylja ,

imagesdir can only be set one time at asciidoctor calls. The editor plugin does this automatically under the hood.
![image](https://user-images.githubusercontent.com/11644753/63699868-fa47db80-c821-11e9-9883-8365dd1b4076.png)

### Why only one directory supported?
Scanning for imagesdir attribute setting takes time and currently all files are scanned. The result
for the images dir is cached and reused to speed up. The images dir is also automatically used in any other file - e.g. in includes. When using a setup like done in https://github.com/arc42/arc42-template/tree/master/EN/asciidoc/src

### Workarounds
1. You could use two projects. "part1" and "part2". Each project should have its own image dir.
2. Use relative pathes instead of images dir

### Potential solution/changes in implementation for future
1. Rendering for files having a `:imagesdir:` attribute inside could ignore the cached
or
2. Service for images dir resolving could scan all files containing attributes and store attributes together with relative pathes from base dir - while rendering a file the nearest imagesdir attribute could be used

I think I would prefer 2.

**Comment by Kylja** [comment]
Hello Albert,

Thanks for your answer.

I did some more testing and it seems that my main problem is that when using the preference "images directory in the preview folder" (as shown in your screenshot) my images are not copied to the images directory in the preview temp directory. 

So to refer to my initial example when I use only part 1 in my project with the mentioned :images: attribute setting. Then the images are not copied from "part1\assets\images\"  to the preview directory "Temp\asciidoctor-editor-temp\project_xxxxxx\images".
When I copy the images myself to this preview directory than the preview works instantly.

When I put the "\images\" directory in the root of the project then everything functions fine. It seems that the application only copies images from the standard images directory to the preview directory and is not able to copy them from an other location?

As for the Potential solution: is it not possibly to find all image files in the project and copy them to the preview images directory?

**Comment by de-jcup** [comment]
Hello Kylia, please do me a favour and create a simple test eclipse project containing your structure.

Then create a zipfile of the complete project and attach it to this issue as described at https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

It would be much more easier to understand and also to implement.

> As for the Potential solution: is it not possibly to find all image files in the project and copy them to the preview images directory?

I think just copying all images would not solve the problem. The paths are important. And the copy mechanism takes time etc. So I try to copy only necessary parts.

**Comment by Kylja** [comment]
Hello Albert,

Your question solved my problem.
To make the requested example for you I made a copy of my project. The surprising thing was that in the copied project the preview worked! 

My initial mistake was that I used:
`
:imagesdir: ../assets/images
`

That does not work but this does:
`
:imagesdir: ./../assets/images
`

I'm not sure why this is, in my opinion both paths point to the same location.

Anyway changing the :imagedir: attribute and saving is not enough to change the file path. It seems the filepath is only changed after using the rebuild function 
![image](https://user-images.githubusercontent.com/28690980/64015099-100c1800-cb24-11e9-88a9-0feef22fc67e.png)

Having a wrong :imagesdir: setting also does not remove the image files already present in the temporary preview image directory. So if you have a correctly setup project than the temporary preview image directory is filled with the images. If the :imagesdir: attribute is then changed to a wrong value than the preview still works (the images are already in the temporary preview directory.

If the project is duplicated in this state than in the new (copied) project the preview does not work. (because the new project uses a new temporary preview directory)
So then there are two identical projects but the preview only works in one.

I have been copying and restructuring my project to get the best directory tree layout (for my purpose) so that and the above probably explains why I got into this situation.

**Comment by de-jcup** [comment]
So as a sum up, implementation changes for this issue will do:

1. **a "rebuild"/"refresh" action does destroy old temp files and create/copy new**
  ( action should not just rebuild the document, but also remove former copied temp  images and copy again - with new path  - so when a image directory is changed and so images are no longer copied, the author should see missing images and not old former copied stuff)
2. **provide a possibiity to handle different imagedir settings in same eclipse project**
  (following approach would fullfill this: _Service for images dir resolving will scan all files containing attributes and store attributes together with relative pathes from base dir - while rendering a file the nearest imagesdir attribute will be used_)

**Comment by Kylja** [comment]
Yes this sum it up!!

I like your solution for item 2.

Greetings

**Comment by de-jcup** [comment]
As information:
https://asciidoctor.org/docs/user-manual/#setting-the-location-of-images

> You can set the imagesdir attribute in multiple places in your document, as long as it is not locked by the API. This technique is useful if you store images for different parts, chapters, or sections of your document in different locations. 

So maybe it will be necessary to handle each document in dedicated way - so nearest path must include the filename as well...

**Comment by de-jcup** [comment]
https://asciidoctor.org/man/asciidoctor/

> Security Settings
> 
> -B, --base-dir=DIR
> 
> Base directory containing the document and resources. Defaults to the directory containing the source file or, if the source is read from a stream, the working directory. When combined with the safe mode setting, can be used to chroot the execution of the program.
> 

Looks like base directory cannot be changed inside documents - as mentioned before

**Comment by de-jcup** [comment]
Could you please tryout Version `2.3.0` on eclipse marketplace - if it is not working out-of-the-box please refer to https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Asciidoctor-configfiles .

Please give me some feedback if this is still an issue.

**Comment by de-jcup** [comment]
@Kylja : I close this issue - please try out the new configuration possibilties with the asciidoctor config file (as mentioned in my last comment) - if there are still any problems please create another issue.
