### ISSUE TITLE
Support spaces in preview temp folder path

### ISSUE THREAD

**Issue by rbioteau** [de-jcup/eclipse-asciidoctor-editor#268]
When having spaces in the preview temp path the absolute to relative path replacement fails.
Spaces are percent encoded in the html and not in the replacement regexp.

I have made a PR to fix this issue: https://github.com/de-jcup/eclipse-asciidoctor-editor/pull/267

**Comment by de-jcup** [comment]
@rbioteau : I appreciate your commitment and your changes/PRs . Thank you very much. 

But currently I am extreme busy at work and running out of time. So it will take some time until I will be able to review and merge your changes. I am sorry!

**Comment by rbioteau** [comment]
I completely understand that you have your own agenda. I'll wait :)

**Comment by de-jcup** [comment]
Merged your changes + added #279
