### ISSUE TITLE
Image file reference validator does not work when file name have spaces

### ISSUE THREAD

**Issue by rbioteau** [de-jcup/eclipse-asciidoctor-editor#270]
Add an image include `image::assets/My image.png`.
The validator shows a warning with the path cut due to the space character.
After some investigation, image include have an `inlined` boolean set to true that have a special behavior for white spaces. I did not understand what this is trying to achieve and what inlined means.

Whitespace issue [here](https://github.com/de-jcup/eclipse-asciidoctor-editor/blob/master/asciidoctor-editor-plugin/src/main/java/de/jcup/asciidoctoreditor/script/AsciiDoctorFileReference.java#L45) and [here](https://github.com/de-jcup/eclipse-asciidoctor-editor/blob/master/asciidoctor-editor-plugin/src/main/java/de/jcup/asciidoctoreditor/script/parser/SimpleReferenceParser.java#L78)

**Comment by de-jcup** [comment]
Added situation to testproject 4, see https://github.com/de-jcup/eclipse-asciidoctor-testprojects/issues/1

**Comment by de-jcup** [comment]
Here output of the example project:

https://github.com/de-jcup/eclipse-asciidoctor-testprojects/blob/master/asciidoctor-testproject5-simple-filenames-with-whitespaces/doc/maindoc-testproject4.adoc

![image](https://user-images.githubusercontent.com/11644753/76535371-0a03d600-647b-11ea-9193-64c251eb08eb.png)

**Comment by de-jcup** [comment]
After last commit we got:

![image](https://user-images.githubusercontent.com/11644753/76540747-e0e74380-6482-11ea-8aab-35a83995b599.png)

**Comment by rbioteau** [comment]
👍
