### ISSUE TITLE
File reference validator does not use :imagesdir: to resolve image file

### ISSUE THREAD

**Issue by rbioteau** [de-jcup/eclipse-asciidoctor-editor#271]
I'll try to have a look if it is complicated to retrieve the `:imagesdir:` value to use it in the [validator](https://github.com/de-jcup/eclipse-asciidoctor-editor/blob/master/asciidoctor-editor-plugin/src/main/java/de/jcup/asciidoctoreditor/script/AsciiDoctorFileReferenceValidator.java#L45)

**Comment by rbioteau** [comment]
I have suggested a fix with PR https://github.com/de-jcup/eclipse-asciidoctor-editor/pull/272

**Comment by de-jcup** [comment]
Hello @rbioteau ,

I have created an feature-branch and merged your proposed PR parts inside.

First of all all thank you.

At the first glance the PR and the issue made sense. After merging the PR and inspecting my own code I found that the `AsciidoctorEditorOutlineSupport` used the imagesDir already as baseDir for validation (see picture below, Line 182). So I tried out without your changes in a real world project and there were no problems.

Here some examples:
- https://github.com/de-jcup/eclipse-asciidoctor-testprojects/blob/master/asciidoctor-testproject2-simple-imagedirset/doc/subfolder1/included.adoc 
- https://github.com/de-jcup/eclipse-asciidoctor-testprojects/blob/master/asciidoctor-testproject2-simple-imagedirset/doc/subfolder1/subfolder1-1/included-2.adoc

![image](https://user-images.githubusercontent.com/11644753/76476110-485caf00-6401-11ea-9727-802ecf117530.png)

### My question
Did you have problems with a real project situation which was not working before or did you just inspect the code and thought there is an issue?
I merged all other changes etc. and made some refinements in 
https://github.com/de-jcup/eclipse-asciidoctor-editor/tree/feature-272-validation-reuses-imagedir
but when we do not really need the change then I am not sure if the PR makes sense - a double check is not necessary.

**Comment by rbioteau** [comment]
Hello @de-jcup ,
I made some tests on your branch and I got issues when image file names contains spaces (and only in that case). That is why I added `isImageReference` in `AsciiDoctorFileReference` and use it in the validator. It is related to the question I asked [here](https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/270)
The addition of the `imageDir` constructor parameter seems indeed useless.

**Comment by de-jcup** [comment]
Hmm. My original API approach of reference validation is a little bit obscure on first sight/usage  but still valid - a `AsciiDoctorEditorReferenceValidator` does just need to now what the `referenceBaseFileOrFolder` is from which the references have their relative path

**I will do following:**
- improve documention
- refactor naming (variables etc.) , so it's more clear what happens
- write tests for whitespace problem with image names containging spaces and fix it
- change valditator tests
- remove setter and imageDir variable inside validator
