### ISSUE TITLE
cannot open pdf preview for non-standart file extensions

### ISSUE THREAD

**Issue by DGarry82** [de-jcup/eclipse-asciidoctor-editor#273]
Steps to reproduce:

1. create empty file (e.g. 'text.txt', extension matters)
2. open with 'Open With -> Other -> Asciidoc editor'
3. add some Asciidoc contents
4. Save using Ctrl-S (dynamic preview will be successfully updated)
5. Press 'Create temporary pdf file and open it' button
6. RESULT: default browser tries to open file "file:///tmp/asciidoctor-editor-temp/project_AsciiDocExample-1261004415/1870582619_hidden-editorfile_**textpdf**" that doesn't exist (see filename suffix, it's '**textpdf**' instead of '**text.pdf**')
7. _WORKAROUND_: just add dot between 'text' and 'pdf in same browser window, and reload page (it means that pdf file itself has been created successfully, onlu url is wrong)

I've tried same with 'text.adoc' file - no problems. But with some file without any extension (e.g. simply '**testfile**') things get even worse - url becomes this : "file:///tmp/asciidoctor-editor-temp/project_AsciiDocExample-1261004415/1726988344_hidden-editorfile_**testpdf**" instead of "file:///tmp/asciidoctor-editor-temp/project_AsciiDocExample-1261004415/1726988344_hidden-editorfile_**testfile.pdf**". Workaround is the same - just to fix url in place.

**Comment by DGarry82** [comment]
(and yes, OS is Debian 9, Eclipse is Neon 4.6)

**Comment by de-jcup** [comment]
Tested with newer eclipse (2019-06) and AsciiDoctor 2.0.3 on Ubuntu based Linux.

Same result:
- text.txt becomes textpdf
- testfile becomes testpdf

Will be fixed

**Comment by de-jcup** [comment]
_Remark: I think this is about ".adoc" usage for file name recalculation to pdf. So always 4 chars.. so dumb implementation has to just become smarter..._

## Todo: 
- write unitests to check these both behaviours
- if necessary write an own class doing the name recalculation for pdf names
- fix the implementation to handle file endings better
  - text.txt must become text.pdf
  - testfile must become testfile.pdf
