### ISSUE TITLE
Wrong reference in File

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#280]
I have a adoc ApacheMaven similar to this:
````
= Maven for building Java applications - Tutorial
include::../10_Include/settings.adoc[]
:vgwort: ApacheMaven
Lars Vogel, Hendrik Still, Simon Scholz (c) 2013 - 2019 vogella GmbH
:author_twitter_handle: vogella
:revnumber:  2.3
:revdate: 11.01.2019

[abstract]
This tutorial describes the usage of Maven for building Java applications.

include::../web/advertisement/afterTableOfContent.adoc[]
include::010_overview.adoc[]
include::012_installation.adoc[]
include::014_usage_commandline.adoc[]
````
On the same folder structure I have multiple other projects one of them is Docker. The link feature sometimes seems to get confused.

![image](https://user-images.githubusercontent.com/139910/73648110-23944f80-467d-11ea-8537-fe1faa836ebc.png)

**Comment by vogella** [comment]
Looks like the tooling sometimes access the wrong directory.

**Comment by vogella** [comment]
Seems to be connected with opened files, if I close all files and open the relevant articles.adoc again, links are fine. Maybe you persist somewhere the path for linkage instead of retrieving it based on the file?

**Comment by de-jcup** [comment]
@vogella I have created a specialized test project  https://github.com/de-jcup/eclipse-asciidoctor-testprojects/issues/2 in branch `issue-280-wrong-references`.

It is always easier to understand a dedicated project setup with an example containing a very similiar structure and setup.

So please do my a favour and make a PR for https://github.com/de-jcup/eclipse-asciidoctor-testprojects/tree/issue-280-wrong-references/asciidoctor-testproject4-vogella-content being similar to your project setup. I already did some examples there, but maybe I am wrong. E.g. maybe the "content" subfolder is not necessary etc.

If you do not like the naming of your company inside the project name please change it.

For more details about the testproject repo please read https://github.com/de-jcup/eclipse-asciidoctor-testprojects/blob/master/README.md

**Comment by de-jcup** [comment]
@vogella I invited you to testprojects repository as collaborator, so you can directly change testproject4... instead of PR...

**Comment by de-jcup** [comment]
When using ASP Server for asciidoc rendering and opening first `001_article.adoc `(Docker) and then `001_article.adoc` (Maven variant) I got a render error from asciidoctor (see picture below). I think the main reason is a wrong root folder calculation. As shown at the output, asciidoctor tries to render these pages.

![image](https://user-images.githubusercontent.com/11644753/73730619-5dc22780-4737-11ea-8f48-3da2ef250cf7.png)

Also many entries about missing files were inside error log (I am not sure if this is related or not, maybe it was only because I did press refresh button to get rid of the error markers)
![image](https://user-images.githubusercontent.com/11644753/73730988-fce71f00-4737-11ea-875e-2a20d30732a3.png)

Last entries as text:
```
File not in current base dir so copied origin as hidden file:/home/albert/dev/projects/jcup/eclipse-asciidoctor-testprojects/asciidoctor-testproject4-vogella-content/content/ApacheMaven/001_article.adoc
File not in current base dir so copied origin as hidden file:/home/albert/dev/projects/jcup/eclipse-asciidoctor-testprojects/asciidoctor-testproject4-vogella-content/content/Docker/001_article.adoc
File not in current base dir so copied origin as hidden file:/home/albert/dev/projects/jcup/eclipse-asciidoctor-testprojects/asciidoctor-testproject4-vogella-content/content/ApacheMaven/001_article-but-other-name.adoc
File not in current base dir so copied origin as hidden file:/home/albert/dev/projects/jcup/eclipse-asciidoctor-testprojects/asciidoctor-testproject4-vogella-content/content/ApacheMaven/001_article.adoc
File not in current base dir so copied origin as hidden file:/home/albert/dev/projects/jcup/eclipse-asciidoctor-testprojects/asciidoctor-testproject4-vogella-content/content/ApacheMaven/001_article-but-other-name.adoc
```
@vogella : 1. Are you using ASP server or native Asciidoctor instance setup? 2. Is my testproject4 setup like yours? (asciidoctor editor tries to resolve document base dir by searching for first directory not containing asciidoc files - so it's important I have created a similar testproject setup to reproduce the problem)

**Comment by vogella** [comment]
Sorry for the delayed reply.

Test setup looks similar to mine. I also have a content folder and multiple folders which follow the same structure, as in your example.

I do not use the editor rendering nor do I look at the result in Eclipse. I run the build via the command line.

**Comment by vogella** [comment]
Thanks, Albert. Is this already published via the normal update side?

**Comment by de-jcup** [comment]
Yes it is. Milestone 2.1.0 is closed and so released. Also v2.1.1 was
already released as well with some additional bugfixes and improvements.

See
https://github.com/de-jcup/eclipse-asciidoctor-editor/releases/tag/v2.1.1

https://github.com/de-jcup/eclipse-asciidoctor-editor/releases/tag/v2.1.0

Greez albert

Lars Vogel <notifications@github.com> schrieb am Di., 17. März 2020, 19:08:

**Comment by vogella** [comment]
Thanks

Albert Tregnaghi <notifications@github.com> schrieb am Di., 17. März 2020,
19:45:
