### ISSUE TITLE
Path to java setting fails on windows

### ISSUE THREAD

**Issue by amarktl** [de-jcup/eclipse-asciidoctor-editor#282]
Using the `ExternalProcessAsciidoctorJServerLauncher` to start a new ASP Server instance fails on windows when setting a custom _pathToJava_ because the check if this is a valid path is faulty.

![Selection_133](https://user-images.githubusercontent.com/24912217/73751609-b86f7980-475f-11ea-9fbb-41a5d55fd3e7.png)

On Windows the java binary is **java.exe**  therefore the check 

`javaCommand = pathToJava + "/java";`
`File test = new File(javaCommand);`
`  if (!test.exists()) {`

will always fail because there is no 'java' file there. 

> [TEA 2020-02-04 14:33:48] AsciiDoctor: >> Not able to start java because not found on defined location:C:\wamas\eclipse\WAMAS-IDE-5_10\binary\openjdk.jdk11.win32.x86_64_1.11.0.5_10\bin/java

My suggestion would be to either

* make this OS-aware `javaCommand = pathToJava + "/java";`
* let the user specify the full path to the java binary. 

I would prefer to specify a full path so there is no more magic which binary is used.

**Comment by de-jcup** [comment]
Will be fixed with ASP 1.1.1 - inside this issue we will:

- change dependency from 1.1.0 to 1.1.1 after 1.1.1 is released
- change preference setup to define absolute/full path to java/java.exe (as suggested by @amarktl )

**Comment by de-jcup** [comment]
Given java path points now to a file - see next picture:
![image](https://user-images.githubusercontent.com/11644753/76427008-15d49700-63ac-11ea-8f64-9f2c1410433f.png)

When field is empty default java implementation is used (as before):
![image](https://user-images.githubusercontent.com/11644753/76427237-57fdd880-63ac-11ea-93be-47161d6bfd4a.png)
