### ISSUE TITLE
Add a clean cache button

### ISSUE THREAD

**Issue by Josar** [de-jcup/eclipse-asciidoctor-editor#286]
When the adoc file is change to a file from an other directory there is an issue to build the preview.

To solve this a clean of the temp folder is neccessary. 
```
file:///tmp/asciidoctor-editor-temp/project_xyz-doc734025281/
```
Could there be a button to delete the temp folder? So it is easier to get this issue tackled.

Maybe it would be a good solution to clean the temp folder when the editor is change to an adoc in a different folder?

**Comment by de-jcup** [comment]
This is related to #210 and also to #257

I think #257 suggestion to cleanup temp folders on a refresh/rebuild action

**Comment by de-jcup** [comment]
Created a new toolbar action - as suggested by @Josar to destroy complete cache (and also internal context, so we always got a fresh one ), also moved both actions (build and clear cache) to own coolbar so easier to find.

![image](https://user-images.githubusercontent.com/11644753/76373054-ab860d00-633f-11ea-9e75-108826895ad5.png)

**Comment by de-jcup** [comment]
Pressing clean button does now show some information in asciidoctor console as well:

![image](https://user-images.githubusercontent.com/11644753/76443078-2c85e880-63c2-11ea-9990-e7f3b6973f48.png)
