### ISSUE TITLE
[Question] Is there a due date for next release ?

### ISSUE THREAD

**Issue by rbioteau** [de-jcup/eclipse-asciidoctor-editor#287]
Hello,
I'd like to know if there is a due date for next release.
I want to integrate the plugin in my RCP next release and I need https://github.com/de-jcup/eclipse-asciidoctor-editor/pull/267 and https://github.com/de-jcup/asp/issues/25

Thanks !

**Comment by de-jcup** [comment]
Hello @rbioteau . Sorry was very busy and then on sick leave... 

Normally I have no explicit release dates - but when you need the changes urgently please tell me your time line - I will try to deploy the next version before your release date so you can use it. Will shrink next milestone a little bit and move incomplete features to next milestone...

Best wishes
Albert

**Comment by rbioteau** [comment]
Hi @de-jcup, thanks for the heads up.
I will integrate an intermediate build of my own if it is not possible on your side. Don't need to rush anything. For info, my target date is early June.

Best regards.
Romain

**Comment by de-jcup** [comment]
Just release Version 2.1.0 on eclipse marketplace
