### ISSUE TITLE
The version 2.1.0 make the `*.txt` file to be associated to the Asciidoctor Editor.

### ISSUE THREAD

**Issue by charleech** [de-jcup/eclipse-asciidoctor-editor#296]
I've just updated the `Asciidoctor Editor` to the latest and greatest version `2.1.0` and found that my `*.txt` files are associated to the  `Asciidoctor Editor` by default. Do we have any configuration to choose whether or not to associate / un-associate  them? 

Anyhow I'm fine with this behavior since I usually use the `Asciidoctor Editor` to write some notes during development and loving it.

My environment is
- Windows 10 Home Edition 1909
-  JDK version 1.8.0_181 64 bits
- Eclipse version 2019-12 (4.14.0)
- Asciidoctor Editor version 2.1.0

**Comment by de-jcup** [comment]
Thanx for reporting.

## Technical description why this happens
With https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/258 this is a side effect.

```xml
   <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
   <!--                          CONTENT TYPE                                -->
   <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
   <extension
         point="org.eclipse.core.contenttype.contentTypes">
      <content-type
            id="de.jcup.asciidoctoreditor.content.asciidoc"
            name="Asciidoc file"
            base-type="org.eclipse.core.runtime.text"
            priority="high">
            <property name="charset" default="UTF-8"/>
      </content-type>
      <file-association
            content-type="de.jcup.asciidoctoreditor.content.asciidoc"
            file-extensions="asciidoc,adoc,asc,ad">
      </file-association>
   </extension>
```

https://help.eclipse.org/2019-12/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_core_contenttype_contentTypes.html

points out:

> base-type - the fully qualified identifier of this content type's base type. This content type will inherit its base type's file associations, content describer and default charset, unless they are redefined

But it is necessary to define `base-type="org.eclipse.core.runtime.text"` to get it working. Normally I have no intention to harm configurations or any other plugins, but currently I have no choice - sorry.

## How to change back *.txt to normal text editor
In main menu open `Window-->Preferences` and enter `file asso` and search for `*.txt` entry.
Then select e.g. normal Text Editor (as shown in next picture)

![image](https://user-images.githubusercontent.com/11644753/76608757-7bdd2d80-6516-11ea-9d61-531404beaee9.png)

Press now the `Default` button:

![image](https://user-images.githubusercontent.com/11644753/76609141-2d7c5e80-6517-11ea-81f4-868fa2233718.png)

After this has been done press the `Apply and close` button and you are done.

**Comment by de-jcup** [comment]
Added link to this issue also to [FAQ](https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/FAQ#my-txt-files-are-associated-with-asciidoctor-editor).

**Comment by famod** [comment]
FWIW, I had to add `*.txt` and `*.log` manually to make it work.
