### ISSUE TITLE
Reference reported as incorrect

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#304]
In the following setup the editor reports that a reference does not exists.

![image](https://user-images.githubusercontent.com/139910/77906971-267c7c80-7289-11ea-8024-c5b058ee1393.png)

Maybe this is the case before a similar file exists somewhere in the workspace?

**Comment by de-jcup** [comment]
Hello, I thought this was already fixed with https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/280. Will try out as soon I will be working on this project again.

**Comment by de-jcup** [comment]
@vogella : Could you please tryout V2.3.0 and give feedback if this is still an issue? I changed a lot - maybe the problem does not occur any longer or can be handled via https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Asciidoctor-configfiles

**Comment by vogella** [comment]
Thank @de-jcup and sorry for the long delay in my response.

Tested with the latest release and seems to work fine.
