### ISSUE TITLE
Includes not found in latest update from marketplace

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#312]
You fixed this issue before, but it is back again for an example: 

![image](https://user-images.githubusercontent.com/139910/81918325-9bf0a200-95d6-11ea-9f67-ec7a9c358cb2.png)

Using:   Asciidoctor Editor	2.1.1	de.jcup.asciidoctoreditor.feature.group	Albert Tregnaghi

**Comment by famod** [comment]
This might help? https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/FAQ#sometimes-my-includes-cannot-be-resolved

**Comment by de-jcup** [comment]
Hello @vogella is this a duplicate for https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/304 or a complete other issue?

Currently I am running out of time - so could you do me a favor and create a PR for https://github.com/de-jcup/eclipse-asciidoctor-testprojects and improve https://github.com/de-jcup/eclipse-asciidoctor-testprojects/tree/master/asciidoctor-testproject4-vogella-content with some more example files, so I have a similar setup for testing.

**Comment by vogella** [comment]
Yes, looks like this is a dup of #304 

@famod refresh did not solve this issue.

Closing as dup of #304
