### ISSUE TITLE
Limit editor to .adoc

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#313]
Since a while the editor feels responsible for pom.xml files and also .project files. Can you restrict it again to .adoc?

![image](https://user-images.githubusercontent.com/139910/81932067-699d6f80-95eb-11ea-8831-bb5d6cb5496d.png)

**Comment by famod** [comment]
This should solve your problem: https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/FAQ#my-txt-files-are-associated-with-asciidoctor-editor

**Comment by de-jcup** [comment]
@vogella : Hello Lars, when I was having the problem with eclipse updates setting Mylyn always again as the new default editor for every `*.adoc` file I asked you about how I could get rid of this problem and - as far as a I remember - you suggested to set priority to high inside plugin.xml to solve this.

see https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/258
To do this you need your own content type and this content type must extend from standard text content type... Unfortunately this does not set priority high for ".adoc" files only but also for ".txt" files which was not intended...

These changes led to exact this situation - as mentioned in
https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/296

My motto is normally "don't do evil plugins..." so maybe I should just eat the frog and remove priority high and accept that Eclipse-Updates will always bring up Mylyn as default asciidoctor editor.
(Except you have a better suggestion)

**Comment by de-jcup** [comment]
@vogella  - was my fault... I accidently registered asciidoc editor for general text content type and not for dedicated asciidoctor editor content type :man_facepalming: ... sorry.

**Comment by vogella** [comment]
Great to hear that this got fixed. Thanks @de-jcup 

Now I don't get a preview anymore if I open a pom.xml :-)
