### ISSUE TITLE
Support asciidoctorconfig files like intellij plugin

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#314]
The intellij plugin supports project specific configuration files
https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations

It's a very clever approach, because so you can fine tune IDE behaviour - this will solve many problems. Every project folder can contain such a configuration file which is accepted by IDE. The idea is to use same format as done in IntelliJ-Plugin, so developers with using both IDEs can work together.

Implementation was done here:
https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/AsciiDoc.java#L424

PS: Thanx to @ahus1 for the nice talk.

**Comment by de-jcup** [comment]
There exists als a gradle plugin to create those files:
https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/master/docs/src/docs/asciidoc/parts/asciidoctoreditorconfig-plugin.adoc

**Comment by de-jcup** [comment]
The asciidoc config file description has moved to https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html


## Sum up

### Supported filenames:
- `.asciidoctorconfig` (origin filename but does not handle ifndef etc.)
- `.asciidoctorconfig.adoc`. This will work the same way like `.asciidoctorconfig` but supports preprocessor macros like `ifndef` 

### Internal processing 
_(Adopted  from intellij documentation  page mentioned before)_

The internal order of processing is as follows:

  -  load the .asciidoctorconfig/.asciidoctorconfig.adoc
      -  file from the root of the project tree (most general configuration)
      -  files from the different directories leading to the specific file to be rendered
      - file from current folder where the file to be rendered resides (most specific to the file opened)
  - Prepend all the files found in the previous steps to the file to be rendered and render it in the preview.

### Provide special variable
The plugin shall also provides a variable `asciidoctorconfigdir` that you can use to set base directory variables.
```
// .asciidoctorconfig
:experimental:
:icons: font

:myprojectbasedir: {asciidoctorconfigdir}
```
When looking at 
https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/3a1adacbec4831fb68759c79d1c2bdf95d32dde0/doc/users-guide/modules/ROOT/pages/features/advanced/stylesheets.adoc as an example of usage, there is described:

> As this uses {asciidoctorconfigdir}, the folder is relative to the .asciidoctorconfig file.

So the variable asciidoctorconfigdir has to be replaced at rendering time with the folder where there current asciidoctorconfig file is located! The last location wins!

An example:
```
$myProjectRoot/
           .asciidoctorconfig.adoc
           main.adoc  -->  {asciidoctorconfigdir} points to $myProjectRoot
           subfolder1/
               .asciidoctorconfig.adoc  
               sub1.adoc -->  {asciidoctorconfigdir} points to $myProjectRoot/subfolder1
               sub1subfolder2/
                      .asciidoctorconfig
                      sub1sub2.adoc  -->  {asciidoctorconfigdir} points to $myProjectRoot/subfolder1/sub1subfolder2/
               sub1subfolder3/
                     sub1sub3.adoc  -->  {asciidoctorconfigdir} points to $myProjectRoot/subfolder1
$myProject
```

**Comment by de-jcup** [comment]
The asciidoc config files do now work same way as in intellij plugin

But there is still one thing not working - when defining a .asciidoctorconfig file like
``` asciidoctor
:imagesdir: {asciidoctorconfigdir}/src/docs/images
```

and writing a asciidoc file doing output:
```
imagesdir = {imagesdir}
```
I don't get the configured value but still values from eclipse given to asciidoctorj.
Maybe it's the document attribute assignment precedence - see https://docs.asciidoctor.org/asciidoc/latest/attributes/assignment-precedence/

@ahus1 : When I look at 

https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/57ad18b78bf1d414f342e87eb706310a491b92fd/src/main/java/org/asciidoc/intellij/AsciiDoc.java#L747-L756

your are not setting the imagesdir attribute like I do with attribute builder in 

https://github.com/de-jcup/eclipse-asciidoctor-editor/blob/6402788af81c79e0db57443ff5dd6dce462de86d/asciidoctor-editor-plugin/src/main/java/de/jcup/asciidoctoreditor/provider/AsciiDoctorOptionsProvider.java#L93

Hmm.. it seems your not setting the basedir at all? I would like to still set the base dir in code but using it as a soft precedence, so provide possiblity to override by user (a workaround would be to not set the attribute in code when defined by user in config file, but... maybe there is a simpler approach) - If you have an idea please add a comment. Thanx.

**Comment by ahus1** [comment]
I set the `basedir`, but not as an attribute, instead as an option on the API, see [AsciiDoc.java#L1068-L1071](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/57ad18b78bf1d414f342e87eb706310a491b92fd/src/main/java/org/asciidoc/intellij/AsciiDoc.java#L1068-L1071)

I would be surprise if a document could overwrite this as an attribute. 

The plugin doesn't set an `imagesdir` as default. Asciidoctor will look in the basedir as default AFAIK.

With the example about `imagesdir` ... I saw something like that happen when a newline is missing; maybe the line `sb.append(configFile.getContentCustomized());` needs to add a newline at the end. I suggest to have a look at the concatenated file before rendering. 

BTW: I prepend the content using a Asciidoctor Preprocessor; this preserves the original line numbers when Asciidoctor logs warnings.

**Comment by de-jcup** [comment]
https://asciidoctor.org/man/asciidoctor/

> Security Settings
> 
> -B, --base-dir=DIR
> 
> Base directory containing the document and resources. Defaults to the directory containing the source file or, if the source is read from a stream, the working directory. When combined with the safe mode setting, can be used to chroot the execution of the program.
> 

Looks like base directory cannot be changed inside documents - as mentioned before
