### ISSUE TITLE
Asciidoctor editor should not be associated to plain text (.txt) files

### ISSUE THREAD

**Issue by jochenschmich** [de-jcup/eclipse-asciidoctor-editor#320]
Hi there,

after installing the Asciidoctor plug-in all plain text files (with the .txt file extension) are associated to the Asciidoctor editor.
This is unfortunate because we don't need the Asciidoctor functionality for plain text files and now we always have to minimize the preview area to make the text more readable.

**Steps to reproduce:**
1. Install the Asciidoctor feature
2. Create a file with the .txt extension
3. (Optional) Open the default editor (via double click)

**Additional information**
I've noticed that the Asciidoctor is associated to every file with the content type "text" and has a higher priority than the default editor.

**Desired behavior**
Plain text files should keep their default file association.

**Proposed fix**
This might be fixed if you'd set "priority" in the [plugin.xml ](https://github.com/de-jcup/eclipse-asciidoctor-editor/blob/6402788af81c79e0db57443ff5dd6dce462de86d/asciidoctor-editor-plugin/plugin.xml#L59) to a lower value than "high".

`<content-type
            id="de.jcup.asciidoctoreditor.content.asciidoc"
            name="Asciidoc file"
            base-type="org.eclipse.core.runtime.text"
            priority="**high**"> 
    <property name="charset" default="UTF-8"/>
</content-type>`

The [Eclipse Extension Point Reference ](https://help.eclipse.org/2019-12/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_core_contenttype_contentTypes.html) says:
> priority - the for this content type. Priorities are used to solve conflicts (when two content types are associated to the same file name/extension)

We'd be very grateful if this could be fixed.

Kind regards,
Jochen

**Comment by anb0s** [comment]
see #313 should be fixed with latest version

**Comment by jochenschmich** [comment]
Thank you very much!
I can confirm, that the problem is now fixed with the latest version.

BTW: https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/FAQ#my-txt-files-are-associated-with-asciidoctor-editor can be deleted or updated.
