### ISSUE TITLE
add support for not installed graphviz (dot)

### ISSUE THREAD

**Issue by anb0s** [de-jcup/eclipse-asciidoctor-editor#322]
We are facing this problem with own distributions without installed graphviz, but delivered with eclipse e.g. in tools folder.

![image](https://user-images.githubusercontent.com/95811/95662606-607fe280-0b38-11eb-9fa7-3d4408262e59.png)

We do not want to add this to Windows system or user PATH as our Eclipse distibution contains all tools.

Would it be possible to configure the path to dot like it's possible in PlantUML plugin also for AsciiDoctor:
![image](https://user-images.githubusercontent.com/95811/95462174-74c8b180-0977-11eb-8135-71dca58aadb1.png)

Thanks!

**Comment by anb0s** [comment]
May be the ASP can be adapted to accept environment variables in `ASPServerAdapter.startServer()` similar to `launcher.setPathToJavaBinary(pathToJavaBinary)`, e.g.: `launcher.setEnvironment(env)` with `Map<String, String> env;` that can be configured by user in the preferences of AsciiDoctor editor in new text field or table with name and value.
`GRAPHVIZ_DOT=tools/graphviz/bin/dot.exe`

ASP would set this if configured:
```
Map<String, String> env = null;
...
ProcessBuilder pb = new ProcessBuilder(command);
if (env != null) {
  Map<String, String> pbEnv = pb.environment();
  pbEnv.putAll(env);
}
```

What do you think?

**Comment by de-jcup** [comment]
Sorry for the late response - I was very busy. Your suggestion should solve the problem.

**Comment by de-jcup** [comment]
Currently still busy because auf #333 and porting all my plugins... After this has been done I will concentrate on solving issues on asciidoctor editor ...

**Comment by de-jcup** [comment]
Hm... Asciidoctor intelliJ seems to do it this way:
https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/57ad18b78bf1d414f342e87eb706310a491b92fd/src/main/java/org/asciidoc/intellij/AsciiDoc.java#L1034-L1037

**Comment by de-jcup** [comment]
With https://github.com/de-jcup/asp/releases/tag/v1.3.0 ASP server can now be started with custom environment entries.

**Comment by de-jcup** [comment]
Either implementation has a configuration page for custom environment entries (in this case ASP and CLI variant must both provide all user entries) - or a dedicated GraphViz preference entry will be set (also in this case ASP and CLI variant are necessary).

**Comment by anb0s** [comment]
> Hm... Asciidoctor intelliJ seems to do it this way:
> https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/57ad18b78bf1d414f342e87eb706310a491b92fd/src/main/java/org/asciidoc/intellij/AsciiDoc.java#L1034-L1037

The solution with Env varibale is also valid and is used in eclox plugin and other doxygen / graphviz / dot  related tools.

Here the customized location without system Env-entry is usefull for multiple Eclipse distributions with all the tools "embedded"...

**Comment by anb0s** [comment]
> Either implementation has a configuration page for custom environment entries (in this case ASP and CLI variant must both provide all user entries) - or a dedicated GraphViz preference entry will be set (also in this case ASP and CLI variant are necessary).

Can we set this manually in a preference file form workspace?

**Comment by de-jcup** [comment]
I created #369 to provide custom environment entries for ASP and also for installed asciidoctor. 
_Will be contained inside Version 2.5.0 (upcoming release on eclipse marketplace in the next weeks)._

Here the screen shot from the feature: 
![image](https://user-images.githubusercontent.com/11644753/132420823-fb471405-640f-41ad-9f65-1f4274c45672.png)

**Comment by de-jcup** [comment]
Hmm... after some tests before releasing, there are some odd situations:
- changing an environment to different value results in 2 or 3 running ASP server instances!  
  Looks like a bug which must be fixed before releasing
- when I set `GRAPHVIZ_DOT` it is inside the JVM process of ASP server, okay, but when using something like `/notexisting/dot" and set it as this environment value, system installed dot will still be used?!?!
- maybe it becomes necessary to install newest graphviz from source (https://gitlab.com/graphviz/graphviz)

**Comment by de-jcup** [comment]
Seems to be necessary to treat the GRAPHVIZ_DOT variable special in ASP. So must wait for https://github.com/de-jcup/asp/issues/44

**Comment by zieglerz** [comment]
Hi :)
We used to setup path to graphviz this way (tools folder inside Eclipse home). But in current version (v3.1.1) this is not working. 

Any ideas, how to solve this? 
![image](https://github.com/de-jcup/eclipse-asciidoctor-editor/assets/85055388/46525db9-a8b2-4933-8b7e-6c9eebc77a78)

Thank you in advance :)


> We are facing this problem with own distributions without installed graphviz, but delivered with eclipse e.g. in tools folder.
> 
> ![image](https://user-images.githubusercontent.com/95811/95662606-607fe280-0b38-11eb-9fa7-3d4408262e59.png)
> 
> We do not want to add this to Windows system or user PATH as our Eclipse distibution contains all tools.
> 
> Would it be possible to configure the path to dot like it's possible in PlantUML plugin also for AsciiDoctor: ![image](https://user-images.githubusercontent.com/95811/95462174-74c8b180-0977-11eb-8135-71dca58aadb1.png)
> 
> Thanks!
