### ISSUE TITLE
Problems rendering images in a multi project.

### ISSUE THREAD

**Issue by junquero** [de-jcup/eclipse-asciidoctor-editor#324]
If I have a maven multi-module project, let's say I have a parent project with 3 modules:

parent/proj1
parent/proj2
parent/proj3

And I create parent/proj1/doc/Readme.adoc and parent/proj1/Readme.png, and the Readme.adoc includes the image:

image::Readme.png[My comment]

The image is not rendered, and a warning is shown:

Validation failed:image::.. references not existing file:C:\path\to\my\parent\Readme.png

I was expecting the editor to lookup for the image on the same folder than the .adoc is, and not in the parent project folder.

It works correctly in Gilab for instance.

**Comment by de-jcup** [comment]
Please try out with current version.

If this is still a problem, please take a look at https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Asciidoctor-configfiles and try to solve it by using a dedicated editor config file.

**Comment by junquero** [comment]
I have been able to manage the issue with your suggestion and the information in https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/257#issuecomment-526567133

With the file .asciidoctorconfig with content
`:imagesdir: ./dbus-etx-producer/doc`

Please note that it is mandatory to add the ./ prefix in the path, and having only dbus-etx-producer/doc doesn't work. This is not what is usually expected, and it was mentioned in the comment referenced before.

Now the images in the doc subfolder is correctly copied to the temporary destination.
Having the definition of imagesdir in the specific configuration file makes the workaround compatible with gitlab which were working correctly without having to specify any imagesdir attribute definition.
