### ISSUE TITLE
Support for older Eclipse

### ISSUE THREAD

**Issue by mfakih294** [de-jcup/eclipse-asciidoctor-editor#326]
Bidirectional support (with proper right-to-left typing e.g. Arabic) seems that got broken in Eclipse editor after version 4.7.3, the last version that I found in my recent investigation. Yet Asciidoctor editor (latest version) requires 4.11 at least. Is it possible that older versions of the plugin support Eclipse 4.7.3?
In this case, how to install it? An update site url or zipped archive site?

**Comment by de-jcup** [comment]
I am sorry - I have currently no idea how to handle this.

But IMHO you should write a bug entry at https://bugs.eclipse.org/bugs/ - it is not okay that the bidirectional support has been broken in eclipse standard editor. This should be fixed there. Having it fixed, all other plugins will benefit from the platform change.

If you have entered a bug there, please add the link here, so I can follow.

**Comment by mfakih294** [comment]
Filed a bug at [bugs.eclipse.org](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569834).
