### ISSUE TITLE
The version 2.3.0 cannot render images from external locations

### ISSUE THREAD

**Issue by charleech** [de-jcup/eclipse-asciidoctor-editor#350]
I've just updated the **eclipse-asciidoctor-editor** version `2.3.0` from **Eclipse Marketplace**  and found that the _Insert Images from a URL_ (https://docs.asciidoctor.org/asciidoc/latest/macros/image-url/) as  _image block_ `image::xxx[]` and _inline image_ `image:` are not rendered as the following screen capture: -

1. The image with static URL
![image-01](https://user-images.githubusercontent.com/1825591/118204145-c7c39380-b487-11eb-8bb6-1bc419d7eee0.jpg)

2. The image with URL from SonarCloud Badge
![image-02](https://user-images.githubusercontent.com/1825591/118204208-e75abc00-b487-11eb-97b0-f168875ff172.jpg)

_Note: I push my code to the **GitHub** and all image blocks are rendered properly._

### Sample Project

I also have a chance to create a minimal sample to reproduce this issue at https://github.com/charleech/eclipse-asciidoctor-sample as the following: -

1. The baseline with simple sample at https://github.com/charleech/eclipse-asciidoctor-sample/blob/main/sample-a/README.adoc

```adoc
= The Eclipse with Asciidoctor Sample : Sample A
Doc Writer <doc@example.com>
:doctype: book
:toc: left
:toclevels: 6

An introduction to http://asciidoc.org[AsciiDoc].

== First Section

* item 1
* item 2

[source,ruby]
puts "Hello, World!"
```

2. The block image reproducer at https://github.com/charleech/eclipse-asciidoctor-sample/blob/main/sample-a/image-01.adoc

```adoc
...
image::https://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg[alt=Tux,width=250,height=350]
```

3. The inline image reproducer at https://github.com/charleech/eclipse-asciidoctor-sample/blob/main/sample-a/image-02.adoc

```adoc
...
image::https://sonarcloud.io/api/project_badges/measure?project=be.yildiz-games%3Amodule-database-updater&metric=alert_status[]
```

### My Environment is
* OS: Windows 10 Home Edition 64 Bits
* JDK: AdoptOpenJDK 1.8.0_292

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```
* Eclipse: 2021-03 (4.19.0) Build id: 20210312-0638
* Asciidoctor Editor: 2.3.0

Could you please help to advise?

**Comment by charleech** [comment]
The structure of the plugins and features are as the following: -

```
+ <eclipse_home>
|--+ plugins
|  |-- + de.jcup.asciidoctoreditor.libs_2.2.0
|  |   |--+ libs
|  |   |   `-- + asp-server-asciidoctorj-dist.jar
|  |   `--+ META-INF
|  |-- de.jcup.asciidoctor.converter_1.1.0.jar
|  |-- de.jcup.asciidoctoreditor.css_1.1.0.jar 
|  `-- de.jcup.asciidoctoreditor_2.3.0.jar 
`-- + features
    `--+ de.jcup.asciidoctoreditor_2.3.0
       `-- feature.xml
```

**Comment by charleech** [comment]
I have a chance to investigate the _generated html file_ at _temp directory_, e.g. `<temp_dir>/asciidoctor-editor-temp/project_sample-a1544271665`.

#### 1. `The image-01.adoc`

There are 3 files generated with _significant <img> tag_ as the following: -
* -384777727_hidden-editorfile_image-01.adoc
* -384777727_hidden-editorfile_image-01.html

```html
<div class="imageblock">
<div class="content">
<!--
Here, the `src` points to the remote URL.
-->
<img src="https://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg" alt="Tux" width="250" height="350">
</div>
</div>
```
* -384777727_internal_image-01.html
  * This may cause our plugin displays an `X` with `alt` as `Tux`
```html
<div class="imageblock">
<div class="content">
<!--
Here the `src` points to the local directory !!!
-->
<img src="PATH_TO_USER\AppData\Local\Temp\asciidoctor-editor-temp\project_sample-a1544271665\img\Tux.svg" alt="Tux" width="250" height="350">
</div>
</div>
```

#### 2. `The image-02.adoc`

_There are only 2 files_ with _significant <img> tag_ as the following: -
* -358341186_hidden-editorfile_image-02.adoc
* -358341186_hidden-editorfile_image-02.html

```html
<div class="imageblock">
<div class="content">
<!--
Here, the `src` points to the remote URL.
-->
<img src="https://sonarcloud.io/api/project_badges/measure?project=be.yildiz-games%3Amodule-database-updater&metric=alert_status" alt="measure?project=be">
</div>
</div>
```

* The expected generated file named ` -358341186_internal_image-02.html` _dose not exist !_
  * This may cause our plugin displays an empty in the preview panel.

**Comment by de-jcup** [comment]
Thanx for reporting!
While refactoring code to handle the image dir location problems I totally missed the situation of having external resources as well and also transformed this URL - yes this is aboslutely a bug.

Will be fixed soon.

**Comment by de-jcup** [comment]
Mentioned example project has now correct preview output:
![image](https://user-images.githubusercontent.com/11644753/118369852-57ab2f80-b5a5-11eb-957c-c8e7bd622290.png)

**Comment by de-jcup** [comment]
@charleech : I just uploaded Version 2.4.0 to eclipse marketplace containing this bugfix  - please tryout...

**Comment by charleech** [comment]
Hi @de-jcup 

I've upgraded the `eclipse-asciidoctor-editor` to version `2.4.0` and found that the image block with `simple static URL` and `URL with query parameter` are rendered properly as the following captured screen: -

### image-01.adoc
![image-01-fixed](https://user-images.githubusercontent.com/1825591/118381998-beb6fb80-b61a-11eb-861e-133be52f0975.jpg)

### image-02.adoc
![image-02-fixed](https://user-images.githubusercontent.com/1825591/118382001-c24a8280-b61a-11eb-9071-6b5895573baf.jpg)

I can confirm that this issue has been solved perfectly.

Thank you very much for your quick upgrade and especially your effort.
