### ISSUE TITLE
Internal preview turns blank after first change

### ISSUE THREAD

**Issue by rolfkleef** [de-jcup/eclipse-asciidoctor-editor#366]
When I open an internal preview on a file, it initially shows the preview. But when switching to another file or application, or saving the same file, the preview turns blank.

Choosing _Reload_ in the context menu does not change anything. When looking with _Inspect Element_, the HTML source looks alright:

![Screenshot from 2021-06-28 14-28-15](https://user-images.githubusercontent.com/223935/123636936-b4913b00-d81d-11eb-81ea-29c8d1ead562.png)

* Using either the ASP version or the installed asciidoctor gives the same result.
* There are no messages in the error log.
* The console log only shows "Installed asciidoctor: Processing .../test.adoc" (or "ASP")
* Eclipse Platform 4.20.0.v20210611-1600
* Asciidoctor Editor 2.4.1
* Ubuntu 21.04

External preview works as a workaround, but I don't seem to find any further clues on what might be happening with the internal preview in the issues here.

**Comment by de-jcup** [comment]
Will try to reproduce, use following snippet:

``` asciidoc
=== Test internal preview
```

**Comment by de-jcup** [comment]
# Tried to reproduce

## Setup
- Linux Mint 20.1 
- Cinammon
- Eclipse 2021-06 (downloaded fresh from https://www.eclipse.org/downloads/packages/release/2021-06/r/eclipse-ide-java-developers )
- installed Asciidoctor editor plugin 2.4.1

## Tried out test snippet
- Opened test snippet, edited etc. no problems
- switched between editors, no problem
![image](https://user-images.githubusercontent.com/11644753/124031806-0e4d5d00-d9f8-11eb-835d-cc524134620d.png)

Pressing `CTRL+SHIFT+_` does also work as expected:

![image](https://user-images.githubusercontent.com/11644753/124032224-95023a00-d9f8-11eb-9b64-a7856a7eac18.png)

pressing `CTRL+S` does update current previews only:
![image](https://user-images.githubusercontent.com/11644753/124032299-b2cf9f00-d9f8-11eb-867e-7d95c28a496b.png)

but pressing the refresh button at the other editor segment does refresh the other part again (a little bit cumbersome but okay - this mode is not often used):

![image](https://user-images.githubusercontent.com/11644753/124033714-97659380-d9fa-11eb-866c-b345067795e1.png)


## Testing with "inspect element"
When pressing "inspect element" on context menu inside preview I have a different output than you:
![image](https://user-images.githubusercontent.com/11644753/124032439-ddb9f300-d9f8-11eb-9855-9d5e28d4c706.png)
This looks different to your screenshots. The SWT browser view should - IMHO - use the system browser. Maybe this is the problem.

## Suggested further steps 
- Update your system browser
- Look into "Error Log" view if there are any GTK errors happening or any other related logs (I would clear the logs and after this start the editor again)
- Try to start with another Linux Window manager and check if the problems still exist

## Conclusion
- I think this is a environment specific problem and not an editor bug

**Comment by rolfkleef** [comment]
Thanks for the effort, @de-jcup! I agree that it's probably some environment-specific problem due to some interaction of Eclipse plugins... I removed the Wildwebdeveloper plugins, which seem to create Eclipse errors, and now it works as expected most of the time. Occasionally, after multiple opens and closes, the view still goes blank.

I'll try more combinations of browsers and windows managers to see if I can get to a reproducible version, and then reopen this issue. As mentioned, it looks like only the SWT browser view goes blank or does not refresh (the HTML source is there), but I don't know if there's a way to probe for events or get more verbose debug logging to see what's going on...

**Comment by rolfkleef** [comment]
For completeness: I have switched back from Wayland to Xorg as window manager for a few days now, which seems to completely resolve the issue.
