### ISSUE TITLE
Support markdown conversion

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#37]
The IntelliJ-Plugin does provide an automated way to convert markdown to asciidoc

Nice feature - should be integrated in eclipse editor as well.
Maybe pandoc would do the trick either?

**Comment by paulvi** [comment]
If you like you can overtake complete https://github.com/winterstein/Eclipse-Markdown-Editor-Plugin/ project or give a fresh alternative

(PS actually that would be meaningful if converting .adoc to .markdown)

**Comment by paulvi** [comment]
For conversion .adoc to .mdown see also https://github.com/bodiam/markdown-to-asciidoc (used by IDEA)

**Comment by de-jcup** [comment]
@paulvi thanks for the link to https://github.com/bodiam/markdown-to-asciidoc . I think I will integrate the library.

**Comment by paulvi** [comment]
Welcome, I would love to see it in 1.0

**Comment by turesheim** [comment]
The WikiText component of the Eclipse Mylyn Docs project is capable of converting between various markup dialects. I don’t have the details ready, but can look it up if there is any interest. See https://projects.eclipse.org/projects/mylyn.docs

**Comment by paulvi** [comment]
@turesheim 
Not listed in Help Content http://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.mylyn.wikitext.help.ui%2Fhelp%2FMylyn-WikiText-User-Guide.html&cp=69_1_0_0&anchor=TableofContents

**Comment by paulvi** [comment]
@turesheim 
Not listed in Help Content http://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.mylyn.wikitext.help.ui%2Fhelp%2FMylyn-WikiText-User-Guide.html&cp=69_1_0_0&anchor=TableofContents

**Comment by turesheim** [comment]
Yes, you won't find this in the user guide. I did look and have to report I'm mistanken. There are means of converting between various Wiki dialects, but Asciidoc is not supported in the result-end. So basically you would create a MarkupParser, configured to read Markdown, then connect it to a DocumentBuilder that produces Asciidoc. Similar to the [MarkdownDocumentBuilder](https://github.com/eclipse/mylyn.docs/blob/master/wikitext/core/org.eclipse.mylyn.wikitext.markdown/src/main/java/org/eclipse/mylyn/wikitext/markdown/internal/MarkdownDocumentBuilder.java). What is missing is a AsciidocDocumentBuilder.

**Comment by de-jcup** [comment]
The idea about the issue is to convert easily an existing documentation in markdown to a asciidoc structure.
I think just using https://github.com/bodiam/markdown-to-asciidoc with a little bit logic around will do the job (when the lib does its job good enough - I did not test it yet)

**Comment by de-jcup** [comment]
Added wiki entry about converter plugin at 
https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Converter
