### ISSUE TITLE
Integrate eclipse-commons library via maven dependency

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#373]
## Situation
Currently `eclipse-commons` library (https://github.com/de-jcup/eclipse-commons)  is directly added into `lib` folder inside Git repository. Having a binary/library inside a GIT repo is normally a very bad idea.  (

## Wanted
No binary version of `eclipse-commons` inside GIT any longer

## Solution
When #371 has been done and https://github.com/de-jcup/eclipse-commons/issues/30 as well, the dependency management shall reference the eclipse-commons library via maven central and the binary from lib folder shall be removed

**Comment by vogella** [comment]
I think we have done this

**Comment by de-jcup** [comment]
Remark: We have done this for the maven - build (#371) . There are still some changes necessary to have the maven build full working, but we have done most parts now and it is okay to close this issue.
