### ISSUE TITLE
Configurable Build-Directory for generated Images

### ISSUE THREAD

**Issue by MH-17** [de-jcup/eclipse-asciidoctor-editor#38]
We have just started to use AsciiDoc and this plugin has been a great help, so thank you for your work.
In our project we use AsciiDoc and AsciiDoc-Diagramm to generate graphs and UML images. The plugin generates and includes the diagrams correctly in the preview window which is great. The images are however stored in the source folder and have to be deleted manually. Could you add a configuration for the AsciiDoc editor which specifies the build directory?

**Comment by de-jcup** [comment]
Hello @MH-17, 
could you please append a zipped example eclipse project where you got documents with graphs and UML images (just examples) as you normally do in your project and where you got the described problem?

So I could simply try it out and better understand your needs (currently I have integrated the support for diagrams, but I don't use it by myself. So if I would have got an example for testing out and also for my own understanding ...)

**Comment by de-jcup** [comment]
@MH-17 Are you really using eclipse and my plugin? I just finished the support of diagrams in #41 right now. Formerly it should have not worked at all.

Funny side is, after implementing #41 there is the problem with the generated pictures from graphviz, ditaa and plantuml that they are created inside images folder.

I created a new issue #42 for the problem - images folder is currently auto detected in sources and it seems this is always used for generated pictures as well. I don't want to make this configurable but to handle the generated files in another way, so I created another issue, which will do also fix the problem but in another way. 

If your are still interested into the solution, please look into #42
