### ISSUE TITLE
PUML includes not working when files are not in project's root folder

### ISSUE THREAD

**Issue by mmoser18** [de-jcup/eclipse-asciidoctor-editor#380]
I created a coupled of .puml files in our project for documentation purposes. Since they became a bit numerous I wanted to move these files to a sep. subdirectory "docs" to keep the root directory less crowded.

Some of my files include others using include-lines like "!include file.puml".

This worked fine when the files were in the root directory but NOT ANYMORE after moving the files to said subdirectory. But also with "!include docs/file.puml" I only get an error message "cannot include docs/file.puml"

When opened with IntelliJ (which also has a PUML plugin) this works fine (without the "docs/"-prefix, i.e. just using the original "!include file.puml" line). How can I convince this to work also in Eclipse with the ascii-editor plugin? What am I missing?

**Comment by de-jcup** [comment]
@mmoser18 : Sorry for the late response.

## Reproducing the problem
I tried to reproduce the problem

```plantuml
@startuml

title I am an example for puml-includes
!include file1.puml
!include puml/file3.puml
@enduml
```

create file structure with `file2.puml` and `file3.puml`
```plantuml
@startuml
title I am included
@enduml
```

![image](https://user-images.githubusercontent.com/11644753/162149282-245974fb-e2f7-40fc-a6fa-2743a7319918.png)

When showing the preview plantuml did complain about not being able to include the plantuml file (file3 in the example)

**Comment by de-jcup** [comment]
I created a test scenario and tried to render 
- test files directly by native asciidoctor by a bash script
- plantuml files by asciidoctor editor directly
- using an intermediate asciidoc file using there a plantuml include 

There were additional issues, which were targeted by #402 , #403 
With #403 it is now able to define the `base_dir` option directly inside the `.asciidoctorconfig.adoc` file so the test scenario (where the native asciidoctor starts deep inside the test project) did also work with the asciidoctor editor.
Then the intermediate asciidoc files did work (which uses the hidden editor files) and no special diagram directory setup was necessary (it behaves like a "normal" asciidoc call)
Only the plantuml files did not work directly. 

This means a fix could be done by changing the way, plantuml temporary files are created.

**Comment by de-jcup** [comment]
The solution was different, for plantuml output generation now always the base directory is set to the parent folder of the original plantuml file inside the eclipse workspace.
