### ISSUE TITLE
Writing document in Greek

### ISSUE THREAD

**Issue by ekekakos** [de-jcup/eclipse-asciidoctor-editor#410]
First of all thanks for this. My issue is if I can write a **Greek document** in Asciidoctor.
I search the internet and I couldn't find sth.
Thanks in advance
Elias

**Comment by ekekakos** [comment]
I put in Eclipse Preferences in Spelling UTF-8 and the problem solved. 
Thanks

**Comment by de-jcup** [comment]
As a late (and more or less additional) answer: Asciidoc does always rely on UTF-8, see https://docs.asciidoctor.org/asciidoc/latest/normalization/ 

> Force the encoding to UTF-8 (An AsciiDoc processor always assumes the content is UTF-8 encoded)
