### ISSUE TITLE
Images not displayed in preview 

### ISSUE THREAD

**Issue by ekekakos** [de-jcup/eclipse-asciidoctor-editor#415]
The images do not displayed in preview (internal or external) while they displayed in PDF.
Is there any solution to this?
Thanks

**Comment by de-jcup** [comment]
I tried two simple examples (one with images, one with plantuml) on both worked in Asciidoc 2.5.0 external, internal and in PDF: 
![image](https://user-images.githubusercontent.com/11644753/166812292-f9346447-3262-40a8-805b-b8dc3d6ac2c5.png)

**Comment by de-jcup** [comment]
Please provide more information:

1. Used asciidoctor editor plugin version
2. Your operation system
3. Your system browser used for external preview
4. Provide a simple example project zip file where I can extract and reproduce

**Comment by de-jcup** [comment]
If you use Windows, I will provide in the next hours a 2.5.1 which does fix #414, maybe this related?

**Comment by de-jcup** [comment]
Also you could try to press the refresh button (toolbar green refresh icon).

**Comment by ekekakos** [comment]
Thanks for the response. I managed to solve it by providing the full pathname of the image file.
image::E:\My Library\eclipse-workspace\Java-Latest-Release\....\images\Lump_Sum_DisplayEL.jpg[]
I tried with **:imagesdir:** but nothing.
As there is a solution I am closing this issue.
Thanks again

**Comment by de-jcup** [comment]
@ekekakos : It should not be necessary to set absolute pathes. When you have trouble with the pathes inside the editor you have also the possiblity to define a (or more) config file(s) to provide a special editor behaviour. See https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Asciidoctor-configfiles#example for an example and the description.
