### ISSUE TITLE
Please add code template for menu

### ISSUE THREAD

**Issue by kikinaer** [de-jcup/eclipse-asciidoctor-editor#422]
Would be nice to have a code template for menus, e.g. menu:File[Open Folder...]

**Comment by de-jcup** [comment]
UI macros are still experimental , see https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/.
So the default templates which are always available inside asciidoctor editor plugin, will not contain this in next future.

But... You can simply define your own templates (and import/export them ).

Just do following:
`Preferences -> Asciidoctor editor -->Templates -> New`  and add your own template - in the next picture I defined it as "menu1". After pressing "Ok" I was able to use the new template inside the editor instances. Please look at the next figure:
![image](https://user-images.githubusercontent.com/11644753/171283003-6a9a88bf-a946-4f73-b3ac-07c2e4e689b4.png)

**Comment by de-jcup** [comment]
@kikinaer - I will close this issue - I think my last comment should have solved your problem/situation.
