### ISSUE TITLE
Plug-in does not expose API -- not able to access editor programmatically

### ISSUE THREAD

**Issue by steghoja** [de-jcup/eclipse-asciidoctor-editor#429]
Hey there,

Wonderful job on the Asciidoc Editor and many others, your work is really appreciated!

I am working on [Eclipse Capra](https://eclipse.org/capra), a traceability management tool. I would like to add a feature to Eclipse Capra that would allow its users create traceability links from and to elements (or `Item`s in the lingo of the plugin) in Asciidoc files. To achieve this, Eclipse Capra needs to be programmatically able to access the editor (to resolve the `TextSelection` the JFace text editor provides to an `Item`). However, this is not possible since the editor does not expose any of its packages as API.

The fix is very simple: by just adding

```
Export-Package: de.jcup.asciidoctoreditor,
  de.jcup.asciidoctoreditor.outline
```

to the `MANIFEST.MF`. I'd be happy to provide a pull request for that, but first wanted to check if that is a desirable change or if you have any concerns about exposing the editor and some of its internals like that.

Thanks for your consideration,
Jan-Philipp

**Comment by de-jcup** [comment]
@steghoja : Good idea, I have no concerns about this and I would appreciate your PR :rocket:

**Comment by steghoja** [comment]
Great! Addressed in PR #432.

**Comment by de-jcup** [comment]
@steghoja  - version 2.6.1 is available on eclipse marketplace now. It contains your changes.

**Comment by steghoja** [comment]
Awesome. thanks so much @de-jcup!
