### ISSUE TITLE
Handle ----+ correctly

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#44]
When using `ditaa` often it comes to something like
`----+` which causes in syntax highlighting problems because its identified as `----`

this must be fixed

**Comment by de-jcup** [comment]
This is not so easy as thought, so moved to 1.0.0

**Comment by paulvi** [comment]
That is similar to highlighting code within code blocks:

from one `\n----` to next `\n----` call external parser. (note the `\n`)

For example for gradle
```
[source,gradle]
----
task wrapper(type: Wrapper) {
    gradleVersion = '4.0'
}
----
```

It should call parser from EGradle Editor. (end exit from it on `\n----`).

Mind-twisting

**Comment by de-jcup** [comment]
A good example for the problem is 19_diagrams_dita_only.adoc:

The output is as follows:

![image](https://user-images.githubusercontent.com/11644753/45746367-662dc700-bc03-11e8-9e43-602aad0710f1.png)

so `-----` shall only identify a token when its the only part inside a line
