### ISSUE TITLE
Error: Could not find Java SE Runtime Environment

### ISSUE THREAD

**Issue by vincenzocaselli** [de-jcup/eclipse-asciidoctor-editor#471]
Hi,
I installed AsciiDoctor Editor 2.7.0 via Eclipse **Marketplace** on 
Eclipse Version: **2022-09 (4.25.0)**

While editing an Asciidoc file I keep on getting this error in console:

```
>> Triggered ASP server start at port:4444
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

>> ASP Server at port 4444 exited with code:Unknown exit code:2

```

I would like to avoid changing the system Java current version from 1.8 back to 1.7.
Is it possible to change it just for the current workspace or anyway to avoid such a global change?
Thank you very much
Vincenzo

**Comment by de-jcup** [comment]
The output is a little bit strange:

> has value '1.8', but '1.7' is required.

Means: Java 8 is installed, but code is compiled with Java 7?

Nevertheless - please use the new Version 3.0.1

There has been done some changes - see https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/458
It uses per default the JRE which is used to run your eclipse. If you have used the eclipse installer it comes with it's own JRE which should be much more newer.

If this does not work, you can install/copy another JRE and set the path inside the preferences (see next picture)
![image](https://user-images.githubusercontent.com/11644753/214256568-18270a23-a7c5-42a6-9394-8fe5615faf2b.png)

Hope this helps.
