### ISSUE TITLE
Cannot connect to the ASP server after a crash

### ISSUE THREAD

**Issue by elecharny** [de-jcup/eclipse-asciidoctor-editor#483]
Hi!

after an eclipse crash (still have to investigate the root cause of this crash), the ASP server is not reachable after the restart:

```
ASP: Processing file:/Users/<blah>
>> Triggered ASP server start at port:4447
...wait for server (2 seconds)
...wait for server (4 seconds)
...wait for server (6 seconds)

>> ASP Server at port 4447 exited with code:Port already in use!:10
...wait for server (8 seconds)
...wait for server (10 seconds)
...wait for server (12 seconds)
...wait for server (14 seconds)
...wait for server (16 seconds)
>> Triggered ASP server start at port:4448
> ASP server not available at port 4448, trigger server restart NOW
```

I had to go to 'preference' and change the port to get it working. I suspect the port is not freed (TIME_WAIT) after the crash.

**Comment by elecharny** [comment]
Thanks a lot !

**Comment by de-jcup** [comment]
For security reasons the ASP server does only communicate with the instance which was starting it. On startup a handshake is done and secret given to the client (eclipse).
This was done for multi user systems, so not everybody can access the documents of another person. Also two different eclipse instances will have 2 different ASP instances running (with two different secret keys).

When eclipse crashes, the plugin stop mechanism was not called - and no ASP stop signal occurred.

With Version 3.1 I have introduced a JVM shutdown hook which stops the ASP (formerly done by plugin stop).
But... not every situation can be handled by this. A hard process termination (SIGKILL)  to eclipse could still make problems.

If you have still such situations (I hope not...) you could also do following on console (Linux):

```
ps aux| grep asp
user     26048  292  1.6 6912216 268924 ?      Sl   15:05   0:17 /the/path/jdk/adopt-jdk/jdk8u282-b08/jre/bin/java -Dasp.server.port=4444 -jar /home/user/.eclipse-asciidoctor-editor/libs/2.4.0/asp-server-asciidoctorj-dist.jar
user     26099  0.0  0.0   9556  2360 pts/0    S+   15:05   0:00 grep --color=auto asp

```
After this
```
kill -9 26048
```
removes the old process.
