### ISSUE TITLE
Preview is not working

### ISSUE THREAD

**Issue by BeckerWdf** [de-jcup/eclipse-asciidoctor-editor#496]
When opening the editor for a docum I don't see a preview. The error log shows:

> java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "de.jcup.asciidoctoreditor.provider.AsciiDoctorWrapperContext.getConfigRoot()" is null
> 	at de.jcup.asciidoctoreditor.asciidoc.AsciiDoctorWrapper.initProviderContext(AsciiDoctorWrapper.java:249)
> 	at de.jcup.asciidoctoreditor.asciidoc.AsciiDoctorWrapper.initContextAndResolveParameters(AsciiDoctorWrapper.java:187)
> 	at de.jcup.asciidoctoreditor.asciidoc.AsciiDoctorWrapper.convert(AsciiDoctorWrapper.java:172)
> 	at de.jcup.asciidoctoreditor.AsciiDoctorEditor$PreviewSupportImpl.convert(AsciiDoctorEditor.java:1448)
> 	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.convertTempAsciidocFileToHTML(AsciidocEditorPreviewBuildRunnnable.java:255)
> 	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.buildHTMLPreviewFile(AsciidocEditorPreviewBuildRunnnable.java:134)
> 	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.run(AsciidocEditorPreviewBuildRunnnable.java:85)
> 	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by zyppe** [comment]
This will happen if only use [Eclipse Platform](https://download.eclipse.org/eclipse/downloads/), but if I start the plugin with [Eclipse IDE for C/C++ Developers](https://www.eclipse.org/downloads/packages/release/2023-09/r/eclipse-ide-cc-developers)" or [Eclipse IDE for Java Developers](https://www.eclipse.org/downloads/packages/release/2023-09/r/eclipse-ide-java-developers) or even install it in [STS](https://spring.io/tools) . Do you miss some package or file that will cause it?

**Comment by zyppe** [comment]
It seems that the preview only work when a project has been opened, why this feature need project?

**Comment by de-jcup** [comment]
> It seems that the preview only work when a project has been opened, why this feature need project?

This is not correct. There is no need for a project. The `getConfigRoot` return value is the location where the configuration is located: Either the base directory of the document or the root configuration file (if there exists one).

But of course it is a bug.

**Comment by de-jcup** [comment]
## How to reproduce
1. Start Eclipse (in my case 2023-09)
2. Ensure Asciidoc editor preferences have enabled preview (vertical or horizontal) per default
3. Create a `test.adoc` at Desktop location and insert some asciidoc content inside
4. drag and drop the file to IDE 
5. The preview cannot be rendered
6. Inside Error Log view we see a NPE

```java
java.lang.NullPointerException
	at de.jcup.asciidoctoreditor.asciidoc.AsciiDoctorWrapper.initProviderContext(AsciiDoctorWrapper.java:249)
	at de.jcup.asciidoctoreditor.asciidoc.AsciiDoctorWrapper.initContextAndResolveParameters(AsciiDoctorWrapper.java:187)
	at de.jcup.asciidoctoreditor.asciidoc.AsciiDoctorWrapper.convert(AsciiDoctorWrapper.java:172)
	at de.jcup.asciidoctoreditor.AsciiDoctorEditor$PreviewSupportImpl.convert(AsciiDoctorEditor.java:1448)
	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.convertTempAsciidocFileToHTML(AsciidocEditorPreviewBuildRunnnable.java:255)
	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.buildHTMLPreviewFile(AsciidocEditorPreviewBuildRunnnable.java:134)
	at de.jcup.asciidoctoreditor.preview.AsciidocEditorPreviewBuildRunnnable.run(AsciidocEditorPreviewBuildRunnnable.java:85)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
