### ISSUE TITLE
A simple DITAA diagramm move and insertion

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#51]
It would be nice to have a simple toolkit inside asciidoctor-plugin toolbar which is able to
- identifiy areas being connected
- select those parts and give possibility to 
  - move blockwise
  - resize components inside editor
- add components. E.g. a box, link etc.

Shall be not sophisticated editor(editor extension), just a more convenient way when starting to
think about a concept and user wants to just draw some boxes and connect them easily.

_I find it some time very hard to define boxes in normal text editor or to refactor/improve existing ditaa diagrams_

**Comment by de-jcup** [comment]
Hm... http://asciiflow.com/ is a nice way to design ditaa files.

Maybe those parts could be a technical inspiration:
- https://github.com/jprichardson/asciiflow/blob/dev/src/com/lewish/asciiflow/client/Canvas.java
- https://github.com/jprichardson/asciiflow/tree/dev/src/com/lewish/asciiflow/client/tools

**Comment by de-jcup** [comment]
https://asciidoctor.org/news/2014/02/18/plain-text-diagrams-in-asciidoctor/

shows a very simple way to include ditaa and plantuml files

e.g. working in a :

-src/

`ditaa::diagrams/diagram_kubernetes_deployment_architecture.ditaa[format=png, alt="Diagram about kubernetes deployment architecture"] `

So instead I will create another project/repository:
https://github.com/de-jcup/ditaa-tools and settle there a simple text editor
where "*.ditaa" files should be editable inside eclipse . So it's also available standalone and seperated...

**Comment by de-jcup** [comment]
With #77 there was a decision to enable DITAA editor as an own descendent editor based on asciidoctor editor.

**Comment by paulvi** [comment]
See also http://www.jave.de/ (listed on https://ascii-uml.github.io/)
that can draw, and move, delete different shapes



![Uploading image.png…]()

**Comment by de-jcup** [comment]
@paulvi - I wrote a mail to the developer of jave (It seems to be no longer developed) to get access to the sources (Its a swing client). Maybe I will get an answer.... If so, it could become easier to implement a better DITAA editor...

**Comment by paulvi** [comment]
I wrote too, but just asking blessing to embed `jave5.jar` in plugin.  

I wonder if Markus % jave is GitHub user.

**Comment by paulvi** [comment]
Markus replies

> Sure, feel free to do that.

for 
Bundle into Eclipse plugin

**Comment by de-jcup** [comment]
@paulvi I think integrating the `jave5.jar` into a plugin is worth its own plugin on eclipse marketplace outside `asciidoctor-editor`. Jave is not only ditaa but a full "**asciiart - paint**". 

When I was using SWTBridge to embedd Swing clients into eclipse many years ago it was a little bit trick but possible.

Do you want to establish a new project at github to embedd java5.jar?

**Comment by paulvi** [comment]
I will not be starting
