### ISSUE TITLE
Introduce the plugin to community

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#52]
Hello @vogella, 
at http://www.vogella.com/tutorials/AsciiDoc/article.html#asciidocwrittertools you are listing some tools for asciidoc . For eclipse you link to https://wiki.eclipse.org/Mylyn/WikiText/AsciiDoc 

I was not comfortable enough with mylyn and the integration so I started my own plugin...
Maybe you are courious and have a look at https://www.youtube.com/playlist?list=PLaBYAz_I_8tFByQ7EWnemjZgx7q-quDyp. There are some short videos showing the editor in action.

I you find it worthful you could link at your page to https://marketplace.eclipse.org/content/asciidoctor-editor too.

Best wishes
Albert

**Comment by vogella** [comment]
Looks cool. "My" killer feature of the Mylyn WikiText editor is the hyperlinking for includes via Ctrl+Mouse click, see screenshot.

![selection_357](https://user-images.githubusercontent.com/139910/40535943-e0d6b3f4-600a-11e8-9ab1-cffa2bfa4f24.png)

Do you have this also in your editor? If yes, I would love to try our editor out.

**Comment by de-jcup** [comment]
Hello @vogella ,

include hyperlinking from editor and also from outline is implemented. I am using the [arc42 ascii doctor template](https://arc42.org/download) in my current business project where I am using includes as well (even with sub-sub includes) and it's working fine. 

Maybe I should create a video with the hyperlinking too.

**Comment by vogella** [comment]
Cool. Can you add a link to your update site? I'm using "our" Eclipse SDK and marketplace is not part of it.

**Comment by vogella** [comment]
Installed Marketplace and afterwards eclipse-asciidoctor-editor

Looks awesome, thanks a bunch for that. I think for the dark theme you could do several improvements, I created issues #62  #61 #60 for that.

**Comment by paulvi** [comment]
@vogella 
Update site is visible for all marketplace entries even before MPC can be used (see image below)

:+1:  for mentioning at http://www.vogella.com/tutorials/AsciiDoc/article.html#asciidocwrittertools
(maybe with some pro and contra)


![image](https://user-images.githubusercontent.com/1614482/40608717-0266fcf4-629f-11e8-8fb1-ac936fe35521.png)

**Comment by vogella** [comment]
@de-jcup do you have a Twitter user?

**Comment by de-jcup** [comment]
Just created [dejcup](https://twitter.com/dejcup) on twitter.

**Comment by paulvi** [comment]
Twitter is no use for China https://no-google-in-china.github.io/

**Comment by vogella** [comment]
@de-jcup Your Asciidoc plug-in and responsiveness is awesome. I switched completely to it and don't use the Mylyn Wikitext editor anymore. I will update my tutorial soon, can't promisse this week, as I have several open customer task. If I don't update this issue by mid-of-next week please ping me. Outside customer work, we are getting Eclipse 4.9 going and I have lots of little areas to look after.

**Comment by de-jcup** [comment]
@vogella - sounds cool. Thank you. And I wish you much success with start of Eclipse 4.9

**Comment by vogella** [comment]
Feel free to jump in with helpful patches. You seems very skilled. :-)

Albert Tregnaghi <notifications@github.com> schrieb am Mi., 30. Mai 2018,
20:32:

**Comment by vogella** [comment]
Sorry for the delay,  http://www.vogella.com/tutorials/AsciiDoc/article.html#asciidocwrittertools has been updated. I think this issue can be closed.

**Comment by vogella** [comment]
@de-jcup I think you are native German speaker. Are you interested in helping with an article in the next Java Magazin about Asciidoc and your Eclipse Support?

**Comment by de-jcup** [comment]
Hello @vogella , reading the german "Java Magazin" since 14 years now I would be glad to help you with an article. And I am native german even when the lastname is italian ;-) 

I will send you an email from my private mail account.
