### ISSUE TITLE
Improve support for the dark theme

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#60]
Currently, the plug-in does not seem to support the dark theme.

Mylyn:

![image](https://user-images.githubusercontent.com/139910/40540650-2a621bea-6019-11e8-9a95-82958e5dd8f6.png)

Your plug-in

![image](https://user-images.githubusercontent.com/139910/40540673-39ed1dbc-6019-11e8-9083-31d60138f299.png)

I found the "Restore Default for the Dark Theme" which provides better styling.

![image](https://user-images.githubusercontent.com/139910/40540730-700cfa48-6019-11e8-84d4-fbee8e222883.png)

Why not setting this via a CSS extension?

You only need the following extension:

```
 <extension
          point="org.eclipse.e4.ui.css.swt.theme">
       <stylesheet
             uri="css/dark-theme.css">
          <themeid
                refid="org.eclipse.e4.ui.css.theme.e4_dark">
          </themeid>
       </stylesheet>
  </extension>

```

pointing to your css and style your preference values.
See here for an example: https://github.com/eclipse/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.themes/css/dark/e4-dark_preferencestyle.css

**Comment by de-jcup** [comment]
Hello @vogella ,

I found your article about themeing http://www.vogella.com/tutorials/Eclipse4CSS/article.html .
Also https://www.eclipse.org/community/eclipse_newsletter/2013/february/article3.php#migration 
describes there is an effort with the migration.

My plugin is not a new e4 plugin but an eclipse 3 plugin, so I am not sure if I can easily use the CSS styling there? 

By the way: When you are using PDT  and you create a new plugin project, you got:
![image](https://user-images.githubusercontent.com/11644753/40550088-79100ad4-6039-11e8-8a7c-502a7bf473be.png)

I am used to use the PDT and the examples coming up with the wizard. So I am still confused, why there is still no easy-to-use e4 integration inside the PDT. When you want to develop e4 plugins you still have to do much work for setting up the e4 development environment. This is the most reason why I am (at least currently) not writing e4 plugins.

**Comment by vogella** [comment]
CSS works well for e3 plugins. Try adding the extension point I listed.

Albert Tregnaghi <notifications@github.com> schrieb am Fr., 25. Mai 2018,
16:38:

**Comment by vogella** [comment]
Wait a minute, I send you a PR soon.

**Comment by vogella** [comment]
This should fix this. As a followup you can remove your Preference dark button. I did not check if you editor updates himself after preference changes, if not you need to close and reopen it after switching the theme.

**Comment by de-jcup** [comment]
@vogella . Thanks a lot. It works well with oxygen.

There are some minor changes necessary. So I will reopen the issue.

**Comment by de-jcup** [comment]
Changes accidently done with message about #63 , origin close commit is a3a7a50
