### ISSUE TITLE
Use png files with transparent background

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#61]
I think it would be nicer if you use png files with transparent background in your toolbar.

![selection_363](https://user-images.githubusercontent.com/139910/40540991-56f6c740-601a-11e8-964b-80ba67e8c110.png)

**Comment by de-jcup** [comment]
ok. will be fixed

**Comment by de-jcup** [comment]
After rework with gimp the icons look nice in dark theme as well (linux system dark theme )
![image](https://user-images.githubusercontent.com/11644753/40568096-ca6684c8-6078-11e8-8586-f934a6351117.png)
