### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#66]
Currently the documentation for the editor is ... poor. 
Either introduce a full blown documentation like in EGradle or do just a Wiki help.

**Comment by de-jcup** [comment]
- [ ] document .ditaa and .plantuml editors

**Comment by kwah-gh** [comment]
Some more things to consider:
* Explain how to set up just _documentation_ project. Currently wiki has a tip about EGradle `java-full-multiproject-with-asciidoctor` template. I have not been able to experiment with it (getting error about gradle not able to detect java version), but the name suggests that it is more than for writing documentation alone
* Maybe also make a how to on hacking the plugin? ;)
* Add tips on how to update 3rd-party plugins, e.g. plantuml. Or maybe make it configurable?

**Comment by de-jcup** [comment]
With #147  an external asciidoctor instance can be used and cli arguments customized.
Documentation was improved in meanwhile too, so closing this issue now.
