### ISSUE TITLE
adoc usage Question: how to inline ASCII drawing?

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-asciidoctor-editor#67]
Just looked at https://github.com/stathissideris/ditaa

But how to inline it within an `.adoc` ?

PS red #53

**Comment by de-jcup** [comment]
Hi @paulvi ,

please look at
https://github.com/de-jcup/eclipse-asciidoctor-editor/blob/master/asciidoctor-editor-other/testscripts/19_diagrams_dita_only.adoc
for an inline example.

Sometimes its preferrable to use link to an external .ditaa file, there is an example for this one at
https://github.com/de-jcup/eclipse-asciidoctor-editor/blob/master/asciidoctor-editor-other/testscripts/23_diagrams_by_macro.adoc

**Comment by paulvi** [comment]
OK, The answer to my question was:

put it between
```
[ditaa]
----
```
and
```
----
```

https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Getting-Started
should have link to 
https://github.com/de-jcup/eclipse-asciidoctor-editor/tree/master/asciidoctor-editor-other/testscripts

**Comment by de-jcup** [comment]
Updated https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Getting-Started as wished.
