### ISSUE TITLE
Internal vs External dependencies

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-asciidoctor-editor#69]
This plugin bundles everything, and becomes fat https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/FAQ#initial-installation-slow-updates-fast

Maybe some users would prefer to use it with local dependencies.  
That would also solve problem about using different version (not the bundled one)

**Comment by de-jcup** [comment]
Good idea, but there is one problem: It's very very tricky to bring asciidoctorj + jruby+ asciidoctor + osgi + eclipse to a stable life... I had BIG problems to stabilize it. And I do not want to have giving support for some local versions or frustrated users where it does not work... 

And its not so much big : asciidoctor libs 1.2 has got 32 MB and css 1.0 has got 6 MB.
Nowadays that not so much, but my own plugin does only have 300 kb. And updates normally do only belong to my own code. So I decided to divide.

The dependencies having one time a 38 MB is not so bad I think.

**Comment by paulvi** [comment]
Not sure if it would decrease download size, but if using doctor via maven plugin https://github.com/asciidoctor/asciidoctor-maven-plugin
it would at least take some pain of checking compatibility of version.

Or use gradle plugin...

**Comment by de-jcup** [comment]
Using maven or gradle for a WYSIWYG integration like this editor is too slow. As a user I want to click `safe `and get the result as fast as possible. This is the great benefit to other integrations. Of course you still need a gradle build integration as well and this sometimes a little bit tricky (or I am too stupid...). So https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/55 mentioned my problems and with EGradle 2.5. there will be an out-of-the-box new project wizard tempate available which contains a full working asciidoc gradle setup with initial chapters etc. See https://github.com/de-jcup/egradle/issues/346

**Comment by de-jcup** [comment]
Having many users wanting new features or a new asciidoctor variant etc. I will create the possibility to have a custom setup too. But the stable and working embedded variant will be kept as is. 

(When one of the custom user setups is stable the embedded one can maybe updated in future ...)  
See also #136 for more information.

**Comment by de-jcup** [comment]
Implemented with #147 , embedded variant based on asciidoctorj 1.5.6 is still contained but users can switch to installed version easily, see #147 for details.

So closing issue.
