### ISSUE TITLE
Link in popup using a dark blue

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#70]
![image](https://user-images.githubusercontent.com/139910/40609518-236cd764-626f-11e8-9ca9-f74398277750.png)

We had this in the past also in Platform but fixed that with https://bugs.eclipse.org/bugs/show_bug.cgi?id=517393
I think you should be able to get the correct color via:

JFaceResources.getColorRegistry().JFacePreferences.HYPERLINK_COLOR);
JFaceResources.getColorRegistry().JFacePreferences.ACTIVE_HYPERLINK_COLOR);

This will work on Photon, not sure about Oxgyen, you may have to check for null in Oxygen and use you own logic. These colors are already styled in the dark theme, so you can use them. 

I suggest to also use them for the xincludes to ensure that everyone understands that these are links.

![image](https://user-images.githubusercontent.com/139910/40609668-a157d26e-626f-11e8-8003-cc2418490672.png)

**Comment by de-jcup** [comment]
Tooltip coloring: just html/css change necessary ( I use browser component there). Should be easy to fix.

about using in Xincludes: Normally only when you use "CTRL+ hoover mouse" over an http adress you have rendered the hyperlink color. Or do you think about using this color always (for normal and CTRL+hoover viewing)

**Comment by vogella** [comment]
> about using in Xincludes

Using different colors for "CTRL+ hoover mouse" and no hoover makes sense. -> No change required for the xinclude text color

**Comment by vogella** [comment]
> Tooltip coloring: just html/css change necessary ( I use browser component there). Should be easy to fix.

Any update here?

**Comment by de-jcup** [comment]
Hello @vogella , I will try to fix it with 1.2.0

**Comment by de-jcup** [comment]
Decided to remove own tooltip support here. Will use eclipse commons tooltip variant instead.

**Comment by de-jcup** [comment]
> I suggest to also use them for the xincludes to ensure that everyone understands that these are links.

I will do so.

**Comment by de-jcup** [comment]
Did remove hyperlink color preferences too in former commit - do now use jface preferences.
