### ISSUE TITLE
Move Preview setting to preferences

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#72]
Currently, I can decided per editor where the preview should be placed.

Preview is a really nice feature, but most of the time I want to have it turned off. Looks to me that I have to set this in every editor again. Would be better IMHO to have a global setting for that.

 This global setting could be overridden in the editor for this editor. Similar to "Show line numbers" in the editor.

**Comment by de-jcup** [comment]
Already possible, the default preview layout is applied to all new opened editors. And - as you suggested - you can change it inside editor again.

![image](https://user-images.githubusercontent.com/11644753/40611943-ad5aa18c-6278-11e8-95e0-3fd8376e6fce.png)

I must improve the documentation...

**Comment by vogella** [comment]
> I must improve the documentation...
Ups, sorry for the noise. I must improve my eyes. :-) No need for any change in the documentation.
