### ISSUE TITLE
No svg preview of pen for 16_images_with_imageDir_set.adoc on Windows 10

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-asciidoctor-editor#74]
No svg preview of pen for `16_images_with_imageDir_set.adoc` on WIndows 10  

and mouse-over image link does not show image

![image](https://user-images.githubusercontent.com/1614482/40622435-3ed2d66a-62d4-11e8-834b-74edc54ad66d.png)

**Comment by paulvi** [comment]
But in external browser (Chrome) is OK
![image](https://user-images.githubusercontent.com/1614482/40622649-32d6d112-62d5-11e8-86ff-96a5551a2004.png)

**Comment by paulvi** [comment]
FYI Also icons are not shown in IE but ok in external Chrome

![image](https://user-images.githubusercontent.com/1614482/40622772-be51b89c-62d5-11e8-90f9-4184c3ec8dc4.png)

**Comment by de-jcup** [comment]
I am not sure if this is a problem because the browsers are showing local resources.

### Idea
If this is the problem an embedded webserver representing the resources could be an option

**Comment by de-jcup** [comment]
@paulvi Is this still an issue ? With https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/134 there were changes done . Currently I have no access to Windows 10, so please test if the problem is solved now and give me short feedback. Thank you.

**Comment by de-jcup** [comment]
Should be fixed with #394 - so I close this issue.
