### ISSUE TITLE
ifndef::condition[] not correctly rendered

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#76]
ifndef::fullscript[] seems not correctly recognized but the editor. 

```
ifndef::fullscript[]
See http://www.vogella.com/tutorials/EclipseGit/article.html[Using Git with the Eclipse IDE] for an introduction into the usage of Git with Eclipse.
endif::fullscript[]
````
![image](https://user-images.githubusercontent.com/139910/40625471-02ea0e0a-62b3-11e8-9115-c3fe5a36baca.png)

**Comment by de-jcup** [comment]
closed with https://github.com/de-jcup/eclipse-asciidoctor-editor/commit/4fb4d5035ae62f44d8953477a27310de5873910b - used accidently wrong issue number.
