### ISSUE TITLE
[not really triffle] Editor for .ditaa, .puml files

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-asciidoctor-editor#77]
Silly idea to support opening *.ditaa files by default within this Editor (associate with .dtaa extention)

and then would save just the need to add

```
[ditaa]
----
```

Other could be enable "Block Selection Mode" (<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd>) 

![image](https://user-images.githubusercontent.com/1614482/40665433-ca5df67c-638f-11e8-9676-d05b697de911.png)

![image](https://user-images.githubusercontent.com/1614482/40665561-1b68e84c-6390-11e8-8452-a776e67f6645.png)

But that would be long way before a sophisticated editor can emerge

ref #67

**Comment by de-jcup** [comment]
Hello @paulvi , an inline editor is not so easy. You are able to include .ditaa files by asciidoctor and a dedicated editor for such file is IMHO much better. See https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/51. At  https://github.com/de-jcup/ditaa-tools maybe - when I got the time... - there will come an editor to live, but I am not sure.

So if you don't mind I close this issue.

**Comment by paulvi** [comment]
Well, https://github.com/de-jcup/ditaa-tools would be of much more work.

The idea was just treat .ditaa files, and do preview using asciidoctor

**Comment by de-jcup** [comment]
Hm... first time was not happy with the idea, but when doing following:

- create another editor ("SimpleDitaaEditor") inside AsciiDoctor-Plugin which extends the editor
- the editor is associated with ".ditaa" files only
- while generating output always the ditaa block is wrapped before generation... so output correct
- when  https://github.com/de-jcup/ditaa-tools comes to real live this editor could use it as a library and
  give more support

**Comment by paulvi** [comment]
exactly, my first step was just to associate with .dtaa #79 (because by default Eclipse tries external programs, just wierd)

https://github.com/de-jcup/ditaa-tools will be super power tools, but for now do something "on the lap" what is possible within 15-50 minutes

**Comment by de-jcup** [comment]
I will add a `SimpleDitaaEditor `or a `AsciiDoctorDitaaEditor` with .ditaa association, so please withdraw your PR #79

**Comment by paulvi** [comment]
just close #79

**Comment by de-jcup** [comment]
Now there are editors included for plantuml and also for ditaa files:

![image](https://user-images.githubusercontent.com/11644753/40945905-039f7ddc-685b-11e8-854d-eed6b89ea3a4.png)

**Comment by paulvi** [comment]
This even deserves own marketplace entry,
as not all looking for diagram editing would think about using ASCII and AsciiDoctor

**Comment by de-jcup** [comment]
@paulvi - sorry, but I think (at least currently) I do not want to add extra marketplace entries only for those smart parts of asciidoctor editor. Reasons:

-  I added the file associations (ditaa, plantuml) to the marketplace entry so it will be found 
- The editors do not have a standalone feature project - would be work again
- The editors cannot exist standalone from asciidoctor editor. It would be too much work to separate
  a core part for those again like done for jenkins-editor. And if so it's always an update issue between
  dependencies of plugins 
- I do not want to have different support issues. if asciidoctor editor is not working both editors
  will also not work. Having same marketplace entry makes it clear
- I do not want to invest work/ create marketplace only few people uses. E.g. 
  https://marketplace.eclipse.org/content/jcup-plugins-collection#group-metrics-tab shows the
  plugin collection seems not to be used by anyone (at least currently). But the setup and the handling 
  took some time which I want to spent in developing of new features instead
- I start running out of time

**Comment by paulvi** [comment]
That was long list of reason, while one would be enough "other priorities"

**Comment by paulvi** [comment]
added mp for this together with plantuml plugin http://plantuml.com/eclipse
ref https://github.com/hallvard/plantuml/issues/58
