### ISSUE TITLE
Use better default colors in the dark theme

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#81]
@de-jcup Are you are dark theme user? For me, the default colors are not optional. So unless you are a dark theme user and have optimized the colors for you, I would like to suggest different colors which would improve the coloring for me.

For example, I like the colors Visual Studio code uses.

If you agree, I could send a PR.

**Comment by de-jcup** [comment]
Hello @vogella please create a PR as suggested.  I am normally not using
DARK theme so you are more target audience than myself...

Greetings Albert

Lars Vogel <notifications@github.com> schrieb am Do., 31. Mai 2018, 10:34:

**Comment by vogella** [comment]
For the header color https://github.com/de-jcup/eclipse-asciidoctor-editor/pull/108

**Comment by vogella** [comment]
Platform switched for normal text to #cccccc in Photon. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=531775 

PR upcoming to use the same in the Asciidoctor dark theme.

**Comment by vogella** [comment]
I'm still not super happy about the colors in the dark theme but I have a hard time finding better onces.
Once I come with a better color I will send a PR, no issue required IMHO.
