### ISSUE TITLE
Provide code templates

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#82]
Mylyn Wiki editor has nice templates for example for creating 
````
[code,java]
====
====
````

Maybe you could add also code templates to your editor. If you need help, please let me know, I should know how to do this. ;-)

**Comment by de-jcup** [comment]
Hello @vogella,

Have you used the Code snippet toolbar Icon already? There are some nice
code snippet integrated.

Of course code templates , maybe editable and extendable by Users, would
be very nice too. I appreciate your offer of help.

If you develop the implementation and give me a PR I will merge it.

**Comment by de-jcup** [comment]
When https://github.com/de-jcup/eclipse-commons/issues/8 is done 
I will integrate eclipse-commons 0.5.0 and use api to provide this to asciidoctor editor

**Comment by de-jcup** [comment]
Hello @vogella  I have now integrated template suppport:

![image](https://user-images.githubusercontent.com/11644753/55441333-b5898280-55aa-11e9-9bab-50345a3f40dd.png)

Please take a look at the plugin.xml where the defaults are defined.
Maybe you got some templates being there as defaults too. Please give me some feedback.

**Comment by de-jcup** [comment]
By the way: Template handling is a little bit different, see https://github.com/de-jcup/eclipse-commons/issues/14, so typing just a part of a template brings up template as well (e.g. for "source java" template you can also type "java" and it wil appear.

**Comment by de-jcup** [comment]
Templates are currently always on top - even when other parts are more relevant.

To handle this eclipse-commons 0.6.0 must be used, which does already adress this.
