### ISSUE TITLE
Some unicode characters are broken during conversion

### ISSUE THREAD

**Issue by mako4** [de-jcup/eclipse-asciidoctor-editor#83]
I encountered a strange problem that some special characters get jumbled in the preview pane.

Here's an example:
````
Test 1 Quotes „test“ (works)

Test 2 Quotes “test” (strange output)

Test 3 Unicode: 世界 (works)
````

The second line gives the following output: `Test 2 Quotes “test��? (strange output)`.

File encoding is UTF-8. I initially thought that this might be a problem with the Internet Explorer renderer, but using the open output in external browser option, I get the same result in Firefox. If I render the same adoc file in Firefox using the asciidoctor.js plugin, there's no problem. 

It does happen with other characters as well, but I have not found a pattern yet.

**Comment by de-jcup** [comment]
Could you please attach an example File. I would integrate it into
testscripts folder and try to fix it.

**Comment by mako4** [comment]
Here is the file (as a txt because github doesn't like adoc).

[test1.txt](https://github.com/de-jcup/eclipse-asciidoctor-editor/files/2063071/test1.txt)

Thanks for the help!

**Comment by de-jcup** [comment]
I will start fixing next week

**Comment by de-jcup** [comment]
At a MINT linux with firefox as system browser I got following output when using master version
### Inside IDE
![image](https://user-images.githubusercontent.com/11644753/40891183-938bb62a-6781-11e8-9768-0205aa7e3a2c.png)
### Opened in external Browser
![image](https://user-images.githubusercontent.com/11644753/40891159-4ae74ee8-6781-11e8-80c7-95da0980ee03.png)

I even tried out old version 0.5.0 but the file was correct rendered also with this version.

**Comment by de-jcup** [comment]
@mako4 : I am having problems to reproduce the bug: At least on Linux I do not get your described problems.

Have you checked settings of your file are really defining the file as UTF-8 inside eclipse? I tried it out and my settings where with UTF-8 as shown in next picture:
![image](https://user-images.githubusercontent.com/11644753/40891268-c40324ae-6782-11e8-9d08-d066efee2e4e.png)

If you have still problems, please give me information which windows version and which internet explorer are you using exactly.  And which eclipse version are you using?

**Comment by de-jcup** [comment]
I was also trying to setup my jvm in another way, so the default character encoding is not UTF-8 and set JVM parameter on eclipse launch : `-Dfile.encoding=ISO-8859-1` to test the behaviour, but even when doing this all was working fine.

**Comment by mako4** [comment]
I use Windows 10, Eclipse 4.7.3 and the latest Internet Explorer (11.48.17134.0). The error happens somewhere before IE as it is also present when viewing the output in other browsers. The file is UTF-8 in the properties dialog.

It is really strange. Testing with the entire Unicode block
````
 	0x00 	0x01 	0x02 	0x03 	0x04 	0x05 	0x06 	0x07 	0x08 	0x09 	0x0A 	0x0B 	0x0C 	0x0D 	0x0E 	0x0F
0x2000 	  	  	  	  	  	  	  	  	  	  	  	​ 	‌ 	‍ 	‎ 	‏
0x2010 	‐ 	‑ 	‒ 	– 	— 	― 	‖ 	‗ 	‘ 	’ 	‚ 	‛ 	“ 	” 	„ 	‟
0x2020 	† 	‡ 	• 	‣ 	․ 	‥ 	… 	‧ 	
0x2030 	‰ 	‱ 	′ 	″ 	‴ 	‵ 	‶ 	‷ 	‸ 	‹ 	› 	※ 	‼ 	‽ 	‾ 	‿
0x2040 	⁀ 	⁁ 	⁂ 	⁃ 	⁄ 	⁅ 	⁆ 	⁇ 	⁈ 	⁉ 	⁊ 	⁋ 	⁌ 	⁍ 	⁎ 	⁏
0x2050 	⁐ 	⁑ 	⁒ 	⁓ 	⁔ 	⁕ 	⁖ 	⁗ 	⁘ 	⁙ 	⁚ 	⁛ 	⁜ 	⁝ 	⁞ 	 
0x2060 	⁠ 	⁡ 	⁢ 	⁣ 	⁤ 	⁥ 	⁫ 	⁬ 	⁭ 	⁮ 	⁯
````
I get this
![grafik](https://user-images.githubusercontent.com/10408999/40900259-111e3402-67cb-11e8-87a1-2e906df4156e.png)
which doesn't really match any character set I know.

Thanks for your help. If I have time, I'll try it today with a Windows 7 machine.

**Comment by de-jcup** [comment]
At windows 7 I got same problems an can reproduce the bug:
![image](https://user-images.githubusercontent.com/11644753/40923858-2cd1594a-6816-11e8-9ea1-7b67466c2d2c.png)
(windows 7 + output on chrome)

**Comment by de-jcup** [comment]
When starting my target eclipse with `-Dfile.encoding=UTF-8` on windows machine the output works well.
Seems to be a problem with file reading and default character encoding.

**Comment by de-jcup** [comment]
@mako4 - the bug is fixed in upcoming version 0.10.0

**Comment by de-jcup** [comment]
@mako4 - version 0.10.0 is released on marketplace and contains the fix.

**Comment by mako4** [comment]
Thanks a lot!
