### ISSUE TITLE
Add possibility to do an auto rebuild for main document

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-asciidoctor-editor#90]
When it comes along with a big documentation and you show the main document for example in browser and you update one of the child pages, you always have to open the main page in editor and click to the refresh button to enable the main page to have got the changes of the child page.

This is reasoned, because every editor instance has its own temporary folder.

But it would be nice to have got the possibility of an automatic rebuild of an document. So the main document could be enabled for auto rebuild, so the complete page would be rebuild including sub pages. 

Maybe this should only be possible when the preview mode is external?

**Comment by de-jcup** [comment]
@vogella What do you think about the idea above?

**Comment by vogella** [comment]
Not sure I understand, but that is most likely because I do not use the preview in the editor. I just tried it again and for me the tooling does not find my include in lots of cases, even though the navigation within Eclipse works fine. 
Example:

![image](https://user-images.githubusercontent.com/139910/44986207-3a63dd80-af83-11e8-850c-cc6aca0ea2c1.png)

**Comment by de-jcup** [comment]
> navigation within Eclipse works fine.

Do you mean 
a) the hyperlinking works well inside editor 
or 
b) the internal preview works but not the external one?

**Comment by vogella** [comment]
> the hyperlinking works well inside editor

This one.

**Comment by de-jcup** [comment]
@vogella : I have problems to recreate the issue in #114 (my own problems are working now...) 
So could you please give me a simple project as zip file where I have a "living bug" you have with includes inside?

Sorry for the inconvenience....

**Comment by de-jcup** [comment]
Include problems should be sovled with #114. 
Also using now one folder for complete project , see #169 

The refresh of an editor preview where child pages are included still keeps sometimes a little bit cumbersome, but a simple refresh on the editor does solve it. A special handling would be too much effort and maybe leads to cross site effects. So closing this issue
