### ISSUE TITLE
xinclude in source statement not support

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#96]
Hyperlinking does not work for the following case for me.

````
[source,xml]
----
include::res/gerrit_java/build.gradle[]
----
`````

**Comment by de-jcup** [comment]
Please create and attach a zipfile containing an example setup  as you did before on another issue https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/71#issuecomment-392523299 . So its much easier to fix.

**Comment by vogella** [comment]
[sourceinclude.zip](https://github.com/de-jcup/eclipse-asciidoctor-editor/files/2081742/sourceinclude.zip)

Attached a small example.
