### ISSUE TITLE
Spell checker support

### ISSUE THREAD

**Issue by uid01089** [de-jcup/eclipse-asciidoctor-editor#99]
Create tool. Only one thing I'm missing is the spell checking support.
Might it be possible to add spell checking services to this create ASCIIDOC-Editor?

Best regards
Konni

**Comment by de-jcup** [comment]
Hello @uid01089 

It should be possible to (re-)integrate a spell checking mechanism as described at
http://blog.ankursharma.org/2009/08/adding-spellchecking-to-custom-editors_19.html

**Comment by de-jcup** [comment]
Works now in following way:

- in normal text parts spellchecking works as normal
- in comments and other asciidoc areas the quick assistent does not
  work, but the spelling hoovers are shown
- enabling spell checking is done as normal in Eclipse preferences for
  text editors.

An example:

![image](https://user-images.githubusercontent.com/11644753/41321970-ba380734-6ea6-11e8-870a-fc7980e87432.png)
